import Erdos993Lean.Analytic.Atlas.Checker

/-!
# The n ≥ 48 strip atlas, piece 00 (band 01) (activity `[1/3, 9/25]`, `m ∈ [221/9, 238/9]`)

Generated by `LEAN/lanes/A20/scratch/gen_strips.py` from lane R4X's
`LEAN/r4x/atlas48_trial/band_01_1-3_9-25/box_*.json` (1 boxes; the saved `dual.alpha` already
contains the constructor's `alpha_adjustment`).  Each box carries its dual's centre `m0` (the box
midpoint) and the checker's hints `N` (explicit cutoff: the Fourier tail applies from `N` on) and
`cm = ⌈m_l⌉`.  The strip is `[floor(n ≥ 48), floor(n ≥ 52)]`: from `k/(2 q(λ_hi))` with the n ≥ 48 rank
`k = 13` to the n ≥ 52 floor.  Tail base: the box's upper activity `lamBox b = qh/(1 − qh)`;
no box is split (smallest margin (2) under the checker's formula: 1.563e-02).
The slabs cover `[q(1/3), q(9/25)] × [221/9, 238/9]` (1 slabs).
-/

namespace Erdos993Lean.Analytic.N48.Data

open Erdos993Lean.Analytic.Atlas

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- r4x/atlas48_trial/band_01_1-3_9-25/box_000000.json -/
def boxP00_000 : Box :=
  ⟨R (1) 4, R (9) 34, R (221) 9, R (238) 9, R (51) 2,
   R (1074238219) 500000000000, R (-112832261) 100000000000,
   R (43391189135841491585325601012296403300313027951) 1063382396627932698323045648224275660800000000000,
   R (2543426967) 1000000000000, R (116550647) 1000000000000,
   [R (1974821347) 7812500000, R (184807641651) 1000000000000, R (34034854857) 250000000000, R (50064668291) 500000000000, R (18379945929) 250000000000, R (53891506791) 1000000000000, R (39447853909) 1000000000000, R (1154181873) 40000000000, R (10560343861) 500000000000, R (15510389253) 1000000000000, R (672530409) 200000000000, R (0) 1, R (0) 1, R (16159579) 62500000000, R (222880441) 125000000000, R (1971623457) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   134, 25⟩

/-- The boxes of the strip P00. -/
def boxesP00 : List Box := [
  boxP00_000
]

/-- The cover slabs of the strip P00. -/
def slabsP00 : List Slab := [
  ⟨R (1) 4, R (9) 34, [0]⟩
]

end Erdos993Lean.Analytic.N48.Data
