import Erdos993Lean.Analytic.Atlas.Checker

/-!
# The n ≥ 48 strip atlas, piece 01 (band 02) (activity `[9/25, 2/5]`, `m ∈ [91/4, 49/2]`)

Generated by `LEAN/lanes/A20/scratch/gen_strips.py` from lane R4X's
`LEAN/r4x/atlas48_trial/band_02_9-25_2-5/box_*.json` (1 boxes; the saved `dual.alpha` already
contains the constructor's `alpha_adjustment`).  Each box carries its dual's centre `m0` (the box
midpoint) and the checker's hints `N` (explicit cutoff: the Fourier tail applies from `N` on) and
`cm = ⌈m_l⌉`.  The strip is `[floor(n ≥ 48), floor(n ≥ 52)]`: from `k/(2 q(λ_hi))` with the n ≥ 48 rank
`k = 13` to the n ≥ 52 floor.  Tail base: the box's upper activity `lamBox b = qh/(1 − qh)`;
no box is split (smallest margin (2) under the checker's formula: 1.902e-03).
The slabs cover `[q(9/25), q(2/5)] × [91/4, 49/2]` (1 slabs).
-/

namespace Erdos993Lean.Analytic.N48.Data

open Erdos993Lean.Analytic.Atlas

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- r4x/atlas48_trial/band_02_9-25_2-5/box_000000.json -/
def boxP01_000 : Box :=
  ⟨R (9) 34, R (2) 7, R (91) 4, R (49) 2, R (189) 8,
   R (1133395817) 500000000000, R (-453726859) 500000000000,
   R (75595263008970306422100968593742915877529164173) 2658455991569831745807614120560689152000000000000,
   R (2834466323) 1000000000000, R (25508827) 200000000000,
   [R (134980362653) 500000000000, R (96501846029) 500000000000, R (138706140483) 1000000000000, R (24879131529) 250000000000, R (7127699229) 100000000000, R (25486983209) 500000000000, R (36423241479) 1000000000000, R (20833381) 800000000, R (18682012177) 1000000000000, R (689392381) 500000000000, R (0) 1, R (5103113577378330895141237258372814524214701473) 2658455991569831745807614120560689152000000000000, R (2011495107) 1000000000000, R (417129047) 125000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   129, 23⟩

/-- The boxes of the strip P01. -/
def boxesP01 : List Box := [
  boxP01_000
]

/-- The cover slabs of the strip P01. -/
def slabsP01 : List Slab := [
  ⟨R (9) 34, R (2) 7, [0]⟩
]

end Erdos993Lean.Analytic.N48.Data
