import Erdos993Lean.Analytic.Atlas.Checker

/-!
# The n ≥ 48 strip atlas, piece 02 (band 03) (activity `[2/5, 9/20]`, `m ∈ [377/18, 203/9]`)

Generated by `LEAN/lanes/A20/scratch/gen_strips.py` from lane R4X's
`LEAN/r4x/atlas48_trial/band_03_2-5_9-20/box_*.json` (2 boxes; the saved `dual.alpha` already
contains the constructor's `alpha_adjustment`).  Each box carries its dual's centre `m0` (the box
midpoint) and the checker's hints `N` (explicit cutoff: the Fourier tail applies from `N` on) and
`cm = ⌈m_l⌉`.  The strip is `[floor(n ≥ 48), floor(n ≥ 52)]`: from `k/(2 q(λ_hi))` with the n ≥ 48 rank
`k = 13` to the n ≥ 52 floor.  Tail base: the box's upper activity `lamBox b = qh/(1 − qh)`;
no box is split (smallest margin (2) under the checker's formula: 1.041e-02).
The slabs cover `[q(2/5), q(9/20)] × [377/18, 203/9]` (2 slabs).
-/

namespace Erdos993Lean.Analytic.N48.Data

open Erdos993Lean.Analytic.Atlas

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- r4x/atlas48_trial/band_03_2-5_9-20/box_000000.json -/
def boxP02_000 : Box :=
  ⟨R (121) 406, R (9) 29, R (377) 18, R (203) 9, R (87) 4,
   R (357178637) 125000000000, R (-603697703) 1000000000000,
   R (54585090134103303570966322061701121298470663281) 1329227995784915872903807060280344576000000000000,
   R (290660073) 100000000000, R (35170497) 200000000000,
   [R (37150084677) 125000000000, R (51085983523) 250000000000, R (140840980777) 1000000000000, R (24230662331) 250000000000, R (66631548599) 1000000000000, R (45822449551) 1000000000000, R (6322209743) 200000000000, R (162860419) 15625000000, R (0) 1, R (2505931722800147237971737330190889438030333499) 1329227995784915872903807060280344576000000000000, R (29498165148004177398384095930687044791442944291) 5316911983139663491615228241121378304000000000000, R (5167185239) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   120, 21⟩

/-- r4x/atlas48_trial/band_03_2-5_9-20/box_000001.json -/
def boxP02_001 : Box :=
  ⟨R (2) 7, R (121) 406, R (377) 18, R (203) 9, R (87) 4,
   R (396482201) 125000000000, R (-69752141) 100000000000,
   R (249887614348691062618942870320266048178446219909) 5316911983139663491615228241121378304000000000000,
   R (203075627) 62500000000, R (176333301) 1000000000000,
   [R (8901529251) 31250000000, R (199157757579) 1000000000000, R (139725962777) 1000000000000, R (97901305879) 1000000000000, R (34272378859) 500000000000, R (12004306861) 250000000000, R (8435443161) 250000000000, R (22391411941) 1000000000000, R (0) 1, R (0) 1, R (13862978923927194468221643012400220216092818187) 5316911983139663491615228241121378304000000000000, R (1028067501) 250000000000, R (2840168771) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   123, 21⟩

/-- The boxes of the strip P02. -/
def boxesP02 : List Box := [
  boxP02_000,
  boxP02_001
]

/-- The cover slabs of the strip P02. -/
def slabsP02 : List Slab := [
  ⟨R (2) 7, R (121) 406, [1]⟩,
  ⟨R (121) 406, R (9) 29, [0]⟩
]

end Erdos993Lean.Analytic.N48.Data
