import Erdos993Lean.Analytic.Atlas.Checker

/-!
# The n ≥ 48 strip atlas, piece 06 (band 07) (activity `[3/5, 13/20]`, `m ∈ [33/2, 231/13]`)

Generated by `LEAN/lanes/A20/scratch/gen_strips.py` from lane R4X's
`LEAN/r4x/atlas48_trial/band_07_3-5_13-20/box_*.json` (2 boxes; the saved `dual.alpha` already
contains the constructor's `alpha_adjustment`).  Each box carries its dual's centre `m0` (the box
midpoint) and the checker's hints `N` (explicit cutoff: the Fourier tail applies from `N` on) and
`cm = ⌈m_l⌉`.  The strip is `[floor(n ≥ 48), floor(n ≥ 52)]`: from `k/(2 q(λ_hi))` with the n ≥ 48 rank
`k = 13` to the n ≥ 52 floor.  Tail base: the box's upper activity `lamBox b = qh/(1 − qh)`;
no box is split (smallest margin (2) under the checker's formula: 3.285e-03).
The slabs cover `[q(3/5), q(13/20)] × [33/2, 231/13]` (2 slabs).
-/

namespace Erdos993Lean.Analytic.N48.Data

open Erdos993Lean.Analytic.Atlas

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- r4x/atlas48_trial/band_07_3-5_13-20/box_000000.json -/
def boxP06_000 : Box :=
  ⟨R (203) 528, R (13) 33, R (33) 2, R (231) 13, R (891) 52,
   R (5996086919) 1000000000000, R (1228871541) 1000000000000,
   R (10357112450106474264321484700315332100137897813) 265845599156983174580761412056068915200000000000,
   R (3075840031) 1000000000000, R (20253253) 62500000000,
   [R (190222578767) 500000000000, R (231429660059) 1000000000000, R (70685468243) 500000000000, R (21830685607) 250000000000, R (27126727403) 1000000000000, R (0) 1, R (81222605529370104984539743728447893000661891337) 5316911983139663491615228241121378304000000000000, R (695403686869250107683363754998490835298507107) 53169119831396634916152282411213783040000000000, R (0) 1, R (371085293) 250000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   106, 17⟩

/-- r4x/atlas48_trial/band_07_3-5_13-20/box_000001.json -/
def boxP06_001 : Box :=
  ⟨R (3) 8, R (203) 528, R (33) 2, R (231) 13, R (891) 52,
   R (6479853287) 1000000000000, R (497159761) 500000000000,
   R (123041697207770606946910045778230029058822537133) 2658455991569831745807614120560689152000000000000,
   R (1460650529) 500000000000, R (202334577) 500000000000,
   [R (368828575887) 1000000000000, R (227308130003) 1000000000000, R (140544900613) 1000000000000, R (10968208051) 125000000000, R (33994401129) 1000000000000, R (0) 1, R (11526367262680919593896034137346616354994690331) 1063382396627932698323045648224275660800000000000, R (4741871406788652837592737012893498657840853951) 332306998946228968225951765070086144000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   107, 17⟩

/-- The boxes of the strip P06. -/
def boxesP06 : List Box := [
  boxP06_000,
  boxP06_001
]

/-- The cover slabs of the strip P06. -/
def slabsP06 : List Slab := [
  ⟨R (3) 8, R (203) 528, [1]⟩,
  ⟨R (203) 528, R (13) 33, [0]⟩
]

end Erdos993Lean.Analytic.N48.Data
