import Erdos993Lean.Analytic.Atlas.Checker

/-!
# The n ≥ 48 strip atlas, piece 07 (band 08) (activity `[13/20, 7/10]`, `m ∈ [221/14, 17]`)

Generated by `LEAN/lanes/A20/scratch/gen_strips.py` from lane R4X's
`LEAN/r4x/atlas48_trial/band_08_13-20_7-10/box_*.json` (2 boxes; the saved `dual.alpha` already
contains the constructor's `alpha_adjustment`).  Each box carries its dual's centre `m0` (the box
midpoint) and the checker's hints `N` (explicit cutoff: the Fourier tail applies from `N` on) and
`cm = ⌈m_l⌉`.  The strip is `[floor(n ≥ 48), floor(n ≥ 52)]`: from `k/(2 q(λ_hi))` with the n ≥ 48 rank
`k = 13` to the n ≥ 52 floor.  Tail base: the box's upper activity `lamBox b = qh/(1 − qh)`;
no box is split (smallest margin (2) under the checker's formula: 4.439e-04).
The slabs cover `[q(13/20), q(7/10)] × [221/14, 17]` (2 slabs).
-/

namespace Erdos993Lean.Analytic.N48.Data

open Erdos993Lean.Analytic.Atlas

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- r4x/atlas48_trial/band_08_13-20_7-10/box_000000.json -/
def boxP07_000 : Box :=
  ⟨R (226) 561, R (7) 17, R (221) 14, R (17) 1, R (459) 28,
   R (1857476283) 250000000000, R (1250855267) 1000000000000,
   R (109105657651489946160556109542766064301683279973) 2658455991569831745807614120560689152000000000000,
   R (245048473) 100000000000, R (444328857) 1000000000000,
   [R (397510246581) 1000000000000, R (234964033817) 1000000000000, R (69995163833) 500000000000, R (40510535047) 500000000000, R (0) 1, R (1816036568797899380712615275073034776770037053) 166153499473114484112975882535043072000000000000, R (23544589236634044189704742365222910548826478947) 1063382396627932698323045648224275660800000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   104, 16⟩

/-- r4x/atlas48_trial/band_08_13-20_7-10/box_000001.json -/
def boxP07_001 : Box :=
  ⟨R (13) 33, R (226) 561, R (221) 14, R (17) 1, R (459) 28,
   R (1751268219) 250000000000, R (31666143) 25000000000,
   R (222741162117907050655060719492108580797943204717) 5316911983139663491615228241121378304000000000000,
   R (358502651) 125000000000, R (453040511) 1000000000000,
   [R (193658139793) 500000000000, R (231726887803) 1000000000000, R (8710657929) 62500000000, R (42527713899) 500000000000, R (1129988317) 125000000000, R (24052890080791359935700976450579172980911227301) 5316911983139663491615228241121378304000000000000, R (98997894645931434601439310395764648646755052093) 5316911983139663491615228241121378304000000000000, R (17011916278900796661821545088984503263411677053) 5316911983139663491615228241121378304000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   105, 16⟩

/-- The boxes of the strip P07. -/
def boxesP07 : List Box := [
  boxP07_000,
  boxP07_001
]

/-- The cover slabs of the strip P07. -/
def slabsP07 : List Slab := [
  ⟨R (13) 33, R (226) 561, [1]⟩,
  ⟨R (226) 561, R (7) 17, [0]⟩
]

end Erdos993Lean.Analytic.N48.Data
