import Erdos993Lean.Analytic.Atlas.Checker

/-!
# The n ≥ 48 strip atlas, piece 32 (band 30) (activity `[9/4, 7/3]`, `m ∈ [85/7, 90/7]`)

Generated by `LEAN/lanes/A20/scratch/gen_strips.py` from lane R4X's
`LEAN/r4x/atlas48_trial/band_30_9-4_7-3/box_*.json` (1 boxes; the saved `dual.alpha` already
contains the constructor's `alpha_adjustment`).  Each box carries its dual's centre `m0` (the box
midpoint) and the checker's hints `N` (explicit cutoff: the Fourier tail applies from `N` on) and
`cm = ⌈m_l⌉`.  The strip is `[floor(n ≥ 48), floor(n ≥ 52)]`: from `k/(2 q(λ_hi))` with the n ≥ 48 rank
`k = 17` to the n ≥ 52 floor.  Tail base: the box's upper activity `lamBox b = qh/(1 − qh)`;
no box is split (smallest margin (2) under the checker's formula: 3.852e-03).
The slabs cover `[q(9/4), q(7/3)] × [85/7, 90/7]` (1 slabs).
-/

namespace Erdos993Lean.Analytic.N48.Data

open Erdos993Lean.Analytic.Atlas

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- r4x/atlas48_trial/band_30_9-4_7-3/box_000000.json -/
def boxP32_000 : Box :=
  ⟨R (9) 13, R (7) 10, R (85) 7, R (90) 7, R (25) 2,
   R (1059752417) 50000000000, R (-482858017) 100000000000,
   R (704762472704875588863214587289186844433339004101) 5316911983139663491615228241121378304000000000000,
   R (946914523) 62500000000, R (110367107) 50000000000,
   [R (249089011987) 1000000000000, R (165094770133) 1000000000000, R (109152360323) 1000000000000, R (72738341281) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   120, 13⟩

/-- The boxes of the strip P32. -/
def boxesP32 : List Box := [
  boxP32_000
]

/-- The cover slabs of the strip P32. -/
def slabsP32 : List Slab := [
  ⟨R (9) 13, R (7) 10, [0]⟩
]

end Erdos993Lean.Analytic.N48.Data
