import Erdos993Lean.Analytic.Atlas.Checker

/-!
# The n ≥ 52 strip atlas, band 01 (activity band `[1/3, 9/25]`, `m ∈ [238/9, 289/9]`)

Generated by `LEAN/lanes/A19/scratch/gen_strip.py` from lane R52's
`LEAN/r52/atlas52_dens/band_01/box_*.json` (1 boxes; the saved `dual.alpha` already
contains the constructor's `alpha_adjustment`).  Each box carries its dual's centre `m0` (the box
midpoint) and the checker's hints `N` (explicit cutoff: the Fourier tail applies from `N` on) and
`cm = ⌈m_l⌉`.  The strip is `[floor(n ≥ 52), floor(n ≥ 61)]`: from `k/(2 q(λ_hi))` with the n ≥ 52 rank
`k = 14` to Profile30's floor.  Tail base: the box's upper activity `lamBox b = qh/(1 − qh)`;
no box is split (smallest margin (2) under the checker's formula: 3.505e-03).
The slabs cover `[q(λ_lo), q(λ_hi)] × [238/9, 289/9]` (1 slabs).
-/

namespace Erdos993Lean.Analytic.N52.Data

open Erdos993Lean.Analytic.Atlas

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- r52/atlas52_dens/band_01/box_000000.json -/
def boxS01_000 : Box :=
  ⟨R (1) 4, R (9) 34, R (238) 9, R (289) 9, R (527) 18,
   R (202066039) 200000000000, R (-25801619) 31250000000,
   R (60927374381657128624636772425195071798699304409) 2658455991569831745807614120560689152000000000000,
   R (184446909) 125000000000, R (29923633) 500000000000,
   [R (10195341937) 40000000000, R (187255232431) 1000000000000, R (34580710843) 250000000000, R (102048593691) 1000000000000, R (7517487399) 100000000000, R (13820607557) 250000000000, R (40574610511) 1000000000000, R (29717136591) 1000000000000, R (10859555327) 500000000000, R (15844645349) 1000000000000, R (1443404513) 125000000000, R (14476881) 50000000000, R (0) 1, R (2047487555165976376800741861832407033744600009) 1329227995784915872903807060280344576000000000000, R (14572926830249135187052452977125359214236393469) 5316911983139663491615228241121378304000000000000, R (2027242873) 1000000000000, R (1153449971) 500000000000, R (160988601) 250000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   134, 27⟩

/-- The boxes of the strip, band 01. -/
def boxesS01 : List Box := [
  boxS01_000
]

/-- The cover slabs of the strip, band 01. -/
def slabsS01 : List Slab := [
  ⟨R (1) 4, R (9) 34, [0]⟩
]

end Erdos993Lean.Analytic.N52.Data
