import Erdos993Lean.Analytic.Atlas.Checker

/-!
# The n ≥ 52 strip atlas, band 30 (activity band `[9/4, 7/3]`, `m ∈ [90/7, 15]`)

Generated by `LEAN/lanes/A19/scratch/gen_strip.py` from lane R52's
`LEAN/r52/atlas52_dens/band_30/box_*.json` (3 boxes; the saved `dual.alpha` already
contains the constructor's `alpha_adjustment`).  Each box carries its dual's centre `m0` (the box
midpoint) and the checker's hints `N` (explicit cutoff: the Fourier tail applies from `N` on) and
`cm = ⌈m_l⌉`.  The strip is `[floor(n ≥ 52), floor(n ≥ 61)]`: from `k/(2 q(λ_hi))` with the n ≥ 52 rank
`k = 18` to Profile30's floor.  Tail base: the box's upper activity `lamBox b = qh/(1 − qh)`;
no box is split (smallest margin (2) under the checker's formula: 1.549e-03).
The slabs cover `[q(λ_lo), q(λ_hi)] × [90/7, 15]` (3 slabs).
-/

namespace Erdos993Lean.Analytic.N52.Data

open Erdos993Lean.Analytic.Atlas

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- r52/atlas52_dens/band_30/box_000000.json -/
def boxS30_000 : Box :=
  ⟨R (181) 260, R (7) 10, R (90) 7, R (15) 1, R (195) 14,
   R (806508969) 50000000000, R (-3463312359) 1000000000000,
   R (666549042779796653298850041570203257580482090833) 5316911983139663491615228241121378304000000000000,
   R (1525938011) 125000000000, R (448901177) 250000000000,
   [R (125827820541) 500000000000, R (41757520301) 250000000000, R (10992708761) 100000000000, R (36018481201) 500000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   120, 13⟩

/-- r52/atlas52_dens/band_30/box_000001.json -/
def boxS30_001 : Box :=
  ⟨R (361) 520, R (181) 260, R (90) 7, R (15) 1, R (195) 14,
   R (15412953443) 1000000000000, R (-1667419787) 500000000000,
   R (2584953840208576608468008049357282260495027099333) 21267647932558653966460912964485513216000000000000,
   R (12540206107) 1000000000000, R (1674601447) 1000000000000,
   [R (257103947207) 1000000000000, R (85204692911) 500000000000, R (112033815001) 1000000000000, R (73345388579) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   119, 13⟩

/-- r52/atlas52_dens/band_30/box_000002.json -/
def boxS30_002 : Box :=
  ⟨R (9) 13, R (361) 520, R (90) 7, R (15) 1, R (195) 14,
   R (7472178087) 500000000000, R (-3222836799) 1000000000000,
   R (2489505893768831000256423819906916586985750785039) 21267647932558653966460912964485513216000000000000,
   R (6374159247) 500000000000, R (1596968103) 1000000000000,
   [R (130338858029) 500000000000, R (86299965027) 500000000000, R (113380529597) 1000000000000, R (7416775989) 100000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   118, 13⟩

/-- The boxes of the strip, band 30. -/
def boxesS30 : List Box := [
  boxS30_000,
  boxS30_001,
  boxS30_002
]

/-- The cover slabs of the strip, band 30. -/
def slabsS30 : List Slab := [
  ⟨R (9) 13, R (361) 520, [2]⟩,
  ⟨R (361) 520, R (181) 260, [1]⟩,
  ⟨R (181) 260, R (7) 10, [0]⟩
]

end Erdos993Lean.Analytic.N52.Data
