import Erdos993Lean.Analytic.Atlas.Checker

/-!
# The n ≥ 45 strip atlas, piece 45 (band 30) (activity `[9/4, 7/3]`, `m ∈ [80/7, 85/7]`)

Generated by `LEAN/lanes/A21/scratch/gen_n.py` from the boxes `LEAN/r4x/atlas45_trial/band_30_9-4_7-3/box_*.json`
(lane R4X's trial strip, 8 boxes, of which the 4 meeting `[floor, cap]` and used by a cover chain are kept;
the saved `dual.alpha` already contains the constructor's `alpha_adjustment`).  Each box carries its dual's centre
`m0` (the box midpoint) and the checker's hints `N` (explicit cutoff: the Fourier tail applies from `N` on) and
`cm = ⌈m_l⌉`.  The strip is `[floor(n ≥ 45), floor(n ≥ 48)]`: from `k/(2 q(λ_hi))` with the n ≥ 45 rank
`k = 16` to the n ≥ 48 floor of the containing piece.  Caps of the piece: `D = 8/5`, `θ = 1`, rates
`1129/2500, 521/1250, 3869/10000, 657/2000, 1369/5000` (t = 0 rate of the parent band).
Tail base: the box's upper activity `lamBox b = qh/(1 − qh)`; no box is split (smallest margin (2) under the
checker's formula: 8.450e-03).  The slabs cover `[q(9/4), q(7/3)] × [80/7, 85/7]` (4 slabs).
-/

namespace Erdos993Lean.Analytic.N45.Data

open Erdos993Lean.Analytic.Atlas

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- r4x/atlas45_trial/band_30_9-4_7-3/box_000001.json -/
def boxP45_000 : Box :=
  ⟨R (363) 520, R (7) 10, R (80) 7, R (85) 7, R (165) 14,
   R (1224292091) 40000000000, R (-2324230119) 250000000000,
   R (15857177891848459690556923390800699287594780459) 85070591730234615865843651857942052864000000000,
   R (13756804953) 1000000000000, R (3295474313) 1000000000000,
   [R (231218740071) 1000000000000, R (38194132047) 250000000000, R (2539869117) 25000000000, R (249602071) 3906250000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   120, 12⟩

/-- r4x/atlas45_trial/band_30_9-4_7-3/box_000003.json -/
def boxP45_001 : Box :=
  ⟨R (181) 260, R (363) 520, R (80) 7, R (85) 7, R (165) 14,
   R (3715837877) 125000000000, R (-230026021) 25000000000,
   R (1916819284056935795076789041466163568035630721991) 10633823966279326983230456482242756608000000000000,
   R (1709359039) 125000000000, R (77983803) 25000000000,
   [R (23674927849) 100000000000, R (1253624751) 8000000000, R (104443268323) 1000000000000, R (35776870577) 500000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   119, 12⟩

/-- r4x/atlas45_trial/band_30_9-4_7-3/box_000005.json -/
def boxP45_002 : Box :=
  ⟨R (361) 520, R (181) 260, R (80) 7, R (85) 7, R (165) 14,
   R (28903390719) 1000000000000, R (-4544498693) 500000000000,
   R (1852398036771424107243990709811302323523254663009) 10633823966279326983230456482242756608000000000000,
   R (13833518261) 1000000000000, R (3001713389) 1000000000000,
   [R (240756118419) 1000000000000, R (159222512709) 1000000000000, R (106007897561) 1000000000000, R (36240213407) 500000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   119, 12⟩

/-- r4x/atlas45_trial/band_30_9-4_7-3/box_000007.json -/
def boxP45_003 : Box :=
  ⟨R (9) 13, R (361) 520, R (80) 7, R (85) 7, R (165) 14,
   R (14043790621) 500000000000, R (-8939860907) 1000000000000,
   R (111856165228102326345083550369620446241733434487) 664613997892457936451903530140172288000000000000,
   R (3496419071) 250000000000, R (144341079) 50000000000,
   [R (1957732093) 8000000000, R (161691560767) 1000000000000, R (840039027) 7812500000, R (36682530447) 500000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   118, 12⟩

/-- The boxes of the strip P45. -/
def boxesP45 : List Box := [
  boxP45_000,
  boxP45_001,
  boxP45_002,
  boxP45_003
]

/-- The cover slabs of the strip P45. -/
def slabsP45 : List Slab := [
  ⟨R (9) 13, R (361) 520, [3]⟩,
  ⟨R (361) 520, R (181) 260, [2]⟩,
  ⟨R (181) 260, R (363) 520, [1]⟩,
  ⟨R (363) 520, R (7) 10, [0]⟩
]

end Erdos993Lean.Analytic.N45.Data
