import Erdos993Lean.Analytic.HandVariance.Compute.Source

/-! Exact source recipes generated by CHECKS/generate_source_data.py.
Source: TWIN v1.8 Appendix N.4; final referee-corrected certfree data.
No floating-point bound is imported as a fact. -/

namespace Erdos993Lean.Analytic.HandVariance.Data
open Compute

def baseChecks : List BaseCheck :=
  [⟨1, ⟨(11/20), (1491/2000)⟩, true⟩,
  ⟨1, ⟨(1491/2000), (387/400)⟩, true⟩,
  ⟨1, ⟨(387/400), (461/400)⟩, true⟩,
  ⟨1, ⟨(461/400), (633/500)⟩, true⟩,
  ⟨1, ⟨(633/500), (1309/1000)⟩, true⟩,
  ⟨1, ⟨(1309/1000), (263/200)⟩, true⟩,
  ⟨0, ⟨(1/3), (2687/6000)⟩, false⟩,
  ⟨0, ⟨(2687/6000), (11/20)⟩, false⟩,
  ⟨2, ⟨(263/200), (3/2)⟩, false⟩,
  ⟨3, ⟨(3/2), (7/4)⟩, false⟩,
  ⟨4, ⟨(7/4), 2⟩, false⟩,
  ⟨5, ⟨2, (58/25)⟩, false⟩,
  ⟨5, ⟨(58/25), (7/3)⟩, false⟩]

end Erdos993Lean.Analytic.HandVariance.Data
