import Erdos993Lean.Analytic.Atlas.Checker

/-!
# The n ≥ 44 strip atlas, piece 00 (band 01) (activity `[1/3, 9/25]`, `m ∈ [68/3, 221/9]`)

Generated by `LEAN/lanes/A21/scratch/gen_n.py` from the boxes `LEAN/r4x/atlas44_trial/band_01_1-3_9-25/box_*.json`
(lane R4X's trial strip, 1 boxes, of which the 1 meeting `[floor, cap]` and used by a cover chain are kept;
the saved `dual.alpha` already contains the constructor's `alpha_adjustment`).  Each box carries its dual's centre
`m0` (the box midpoint) and the checker's hints `N` (explicit cutoff: the Fourier tail applies from `N` on) and
`cm = ⌈m_l⌉`.  The strip is `[floor(n ≥ 44), floor(n ≥ 45)]`: from `k/(2 q(λ_hi))` with the n ≥ 44 rank
`k = 12` to the n ≥ 45 floor of the containing piece.  Caps of the piece: `D = 8/5`, `θ = 1`, rates
`619/2500, 2353/10000, 551/2500, 489/2500, 169/1000` (t = 0 rate of the parent band).
Tail base: the box's upper activity `lamBox b = qh/(1 − qh)`; no box is split (smallest margin (2) under the
checker's formula: 8.565e-03).  The slabs cover `[q(1/3), q(9/25)] × [68/3, 221/9]` (1 slabs).
-/

namespace Erdos993Lean.Analytic.N44.Data

open Erdos993Lean.Analytic.Atlas

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- r4x/atlas44_trial/band_01_1-3_9-25/box_000000.json -/
def boxP00_000 : Box :=
  ⟨R (1) 4, R (9) 34, R (68) 3, R (238) 9, R (221) 9,
   R (461662841) 200000000000, R (-291070651) 250000000000,
   R (222928778484544120416237764175914608514975533221) 5316911983139663491615228241121378304000000000000,
   R (349419097) 125000000000, R (35493153) 250000000000,
   [R (251696308827) 1000000000000, R (183726914287) 1000000000000, R (33782677069) 250000000000, R (49596320821) 500000000000, R (18163776247) 250000000000, R (26549422137) 500000000000, R (7745441521) 200000000000, R (7051479183) 250000000000, R (10272036921) 500000000000, R (3001158317) 200000000000, R (19508137) 20000000000, R (0) 1, R (0) 1, R (0) 1, R (38906437) 25000000000, R (259733589) 500000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   134, 23⟩

/-- The boxes of the strip P00. -/
def boxesP00 : List Box := [
  boxP00_000
]

/-- The cover slabs of the strip P00. -/
def slabsP00 : List Slab := [
  ⟨R (1) 4, R (9) 34, [0]⟩
]

end Erdos993Lean.Analytic.N44.Data
