import Erdos993Lean.Analytic.Atlas.Checker

/-!
# The n ≥ 44 strip atlas, piece 01 (band 02) (activity `[9/25, 2/5]`, `m ∈ [21, 91/4]`)

Generated by `LEAN/lanes/A21/scratch/gen_n.py` from the boxes `LEAN/r4x/atlas44_trial/band_02_9-25_2-5/box_*.json`
(lane R4X's trial strip, 2 boxes, of which the 2 meeting `[floor, cap]` and used by a cover chain are kept;
the saved `dual.alpha` already contains the constructor's `alpha_adjustment`).  Each box carries its dual's centre
`m0` (the box midpoint) and the checker's hints `N` (explicit cutoff: the Fourier tail applies from `N` on) and
`cm = ⌈m_l⌉`.  The strip is `[floor(n ≥ 44), floor(n ≥ 45)]`: from `k/(2 q(λ_hi))` with the n ≥ 44 rank
`k = 12` to the n ≥ 45 floor of the containing piece.  Caps of the piece: `D = 8/5`, `θ = 1`, rates
`1309/5000, 613/2500, 2327/10000, 509/2500, 439/2500` (t = 0 rate of the parent band).
Tail base: the box's upper activity `lamBox b = qh/(1 − qh)`; no box is split (smallest margin (2) under the
checker's formula: 1.056e-02).  The slabs cover `[q(9/25), q(2/5)] × [21, 91/4]` (2 slabs).
-/

namespace Erdos993Lean.Analytic.N44.Data

open Erdos993Lean.Analytic.Atlas

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- r4x/atlas44_trial/band_02_9-25_2-5/box_000000.json -/
def boxP01_000 : Box :=
  ⟨R (131) 476, R (2) 7, R (21) 1, R (49) 2, R (91) 4,
   R (273439397) 100000000000, R (-506069289) 500000000000,
   R (62959010305212580948526184659768747963547568557) 1329227995784915872903807060280344576000000000000,
   R (2971971227) 1000000000000, R (180722003) 1000000000000,
   [R (68376275321) 250000000000, R (193613400583) 1000000000000, R (17225857807) 125000000000, R (48936982811) 500000000000, R (34681376981) 500000000000, R (49069876697) 1000000000000, R (34690401807) 1000000000000, R (24565843541) 1000000000000, R (5000830839) 500000000000, R (0) 1, R (0) 1, R (9144766535642102956390020049996582004311181209) 5316911983139663491615228241121378304000000000000, R (721097011) 250000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   126, 21⟩

/-- r4x/atlas44_trial/band_02_9-25_2-5/box_000001.json -/
def boxP01_001 : Box :=
  ⟨R (9) 34, R (131) 476, R (21) 1, R (49) 2, R (91) 4,
   R (3029340981) 1000000000000, R (-55335667) 50000000000,
   R (14143566303465622388527335226437568954308513539) 265845599156983174580761412056068915200000000000,
   R (1632971397) 500000000000, R (171650193) 1000000000000,
   [R (1317110797) 5000000000, R (47279065219) 250000000000, R (27339520277) 200000000000, R (12330206443) 125000000000, R (71071083223) 1000000000000, R (12788820993) 250000000000, R (36827787773) 1000000000000, R (26579987603) 1000000000000, R (19310536951) 1000000000000, R (297863203) 250000000000, R (0) 1, R (0) 1, R (256244037) 200000000000, R (3129396427) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   129, 21⟩

/-- The boxes of the strip P01. -/
def boxesP01 : List Box := [
  boxP01_000,
  boxP01_001
]

/-- The cover slabs of the strip P01. -/
def slabsP01 : List Slab := [
  ⟨R (9) 34, R (131) 476, [1]⟩,
  ⟨R (131) 476, R (2) 7, [0]⟩
]

end Erdos993Lean.Analytic.N44.Data
