import Erdos993Lean.Analytic.Atlas.Checker

/-!
# The n ≥ 44 strip atlas, piece 02 (band 03) (activity `[2/5, 9/20]`, `m ∈ [58/3, 377/18]`)

Generated by `LEAN/lanes/A21/scratch/gen_n.py` from the boxes `LEAN/r4x/atlas44_trial/band_03_2-5_9-20/box_*.json`
(lane R4X's trial strip, 2 boxes, of which the 2 meeting `[floor, cap]` and used by a cover chain are kept;
the saved `dual.alpha` already contains the constructor's `alpha_adjustment`).  Each box carries its dual's centre
`m0` (the box midpoint) and the checker's hints `N` (explicit cutoff: the Fourier tail applies from `N` on) and
`cm = ⌈m_l⌉`.  The strip is `[floor(n ≥ 44), floor(n ≥ 45)]`: from `k/(2 q(λ_hi))` with the n ≥ 44 rank
`k = 12` to the n ≥ 45 floor of the containing piece.  Caps of the piece: `D = 8/5`, `θ = 1`, rates
`2793/10000, 2617/10000, 2451/10000, 271/1250, 467/2500` (t = 0 rate of the parent band).
Tail base: the box's upper activity `lamBox b = qh/(1 − qh)`; no box is split (smallest margin (2) under the
checker's formula: 5.299e-03).  The slabs cover `[q(2/5), q(9/20)] × [58/3, 377/18]` (2 slabs).
-/

namespace Erdos993Lean.Analytic.N44.Data

open Erdos993Lean.Analytic.Atlas

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- r4x/atlas44_trial/band_03_2-5_9-20/box_000000.json -/
def boxP02_000 : Box :=
  ⟨R (121) 406, R (9) 29, R (58) 3, R (203) 9, R (377) 18,
   R (3625166773) 1000000000000, R (-345743991) 1000000000000,
   R (260253209307775221801527080099466216684989637697) 5316911983139663491615228241121378304000000000000,
   R (349372697) 100000000000, R (37997127) 200000000000,
   [R (1185050869) 4000000000, R (51023056237) 250000000000, R (140759615233) 1000000000000, R (97011627379) 1000000000000, R (66890870253) 1000000000000, R (9250422961) 200000000000, R (1006595549) 31250000000, R (296827357) 40000000000, R (0) 1, R (13168489201871793848780223349662557379071551677) 5316911983139663491615228241121378304000000000000, R (33518355438899148971315174104032704681410369497) 5316911983139663491615228241121378304000000000000, R (3681258353) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   120, 20⟩

/-- r4x/atlas44_trial/band_03_2-5_9-20/box_000001.json -/
def boxP02_001 : Box :=
  ⟨R (2) 7, R (121) 406, R (58) 3, R (203) 9, R (377) 18,
   R (3271627017) 1000000000000, R (-601833597) 1000000000000,
   R (30258808953484114025588089485163516376762675461) 664613997892457936451903530140172288000000000000,
   R (919488287) 250000000000, R (186191137) 1000000000000,
   [R (28414864433) 100000000000, R (49671388933) 250000000000, R (69645237579) 500000000000, R (12187816561) 125000000000, R (17045674639) 250000000000, R (4769188251) 100000000000, R (16726570969) 500000000000, R (21159325819) 1000000000000, R (0) 1, R (0) 1, R (12763037871384052648802504331639958799997542103) 5316911983139663491615228241121378304000000000000, R (197448533) 50000000000, R (233399509) 200000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   123, 20⟩

/-- The boxes of the strip P02. -/
def boxesP02 : List Box := [
  boxP02_000,
  boxP02_001
]

/-- The cover slabs of the strip P02. -/
def slabsP02 : List Slab := [
  ⟨R (2) 7, R (121) 406, [1]⟩,
  ⟨R (121) 406, R (9) 29, [0]⟩
]

end Erdos993Lean.Analytic.N44.Data
