import Erdos993Lean.Analytic.Atlas.Checker

/-!
# The n ≥ 44 strip atlas, piece 03 (band 04) (activity `[9/20, 1/2]`, `m ∈ [18, 39/2]`)

Generated by `LEAN/lanes/A21/scratch/gen_n.py` from the boxes `LEAN/r4x/atlas44_trial/band_04_9-20_1-2/box_*.json`
(lane R4X's trial strip, 2 boxes, of which the 2 meeting `[floor, cap]` and used by a cover chain are kept;
the saved `dual.alpha` already contains the constructor's `alpha_adjustment`).  Each box carries its dual's centre
`m0` (the box midpoint) and the checker's hints `N` (explicit cutoff: the Fourier tail applies from `N` on) and
`cm = ⌈m_l⌉`.  The strip is `[floor(n ≥ 44), floor(n ≥ 45)]`: from `k/(2 q(λ_hi))` with the n ≥ 44 rank
`k = 12` to the n ≥ 45 floor of the containing piece.  Caps of the piece: `D = 8/5`, `θ = 1`, rates
`751/2500, 563/2000, 1333/5000, 291/1250, 1001/5000` (t = 0 rate of the parent band).
Tail base: the box's upper activity `lamBox b = qh/(1 − qh)`; no box is split (smallest margin (2) under the
checker's formula: 5.313e-03).  The slabs cover `[q(9/20), q(1/2)] × [18, 39/2]` (2 slabs).
-/

namespace Erdos993Lean.Analytic.N44.Data

open Erdos993Lean.Analytic.Atlas

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- r4x/atlas44_trial/band_04_9-20_1-2/box_000000.json -/
def boxP03_000 : Box :=
  ⟨R (28) 87, R (1) 3, R (18) 1, R (21) 1, R (39) 2,
   R (4922604891) 1000000000000, R (90975121) 500000000000,
   R (145054110099480213062579203144647486034040724377) 2658455991569831745807614120560689152000000000000,
   R (858281097) 250000000000, R (271830893) 1000000000000,
   [R (15875865863) 50000000000, R (105902386183) 500000000000, R (28249279067) 200000000000, R (4716308283) 50000000000, R (6330055231) 100000000000, R (42962698213) 1000000000000, R (5816248619) 1000000000000, R (0) 1, R (30909913054664768471834066663354872457463930413) 5316911983139663491615228241121378304000000000000, R (5225050423442010411228790434025932103097955093) 531691198313966349161522824112137830400000000000, R (476578279) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   115, 18⟩

/-- r4x/atlas44_trial/band_04_9-20_1-2/box_000001.json -/
def boxP03_001 : Box :=
  ⟨R (9) 29, R (28) 87, R (18) 1, R (21) 1, R (39) 2,
   R (4536825951) 1000000000000, R (-4734321) 31250000000,
   R (28406785453839842464825834009322067428131356649) 531691198313966349161522824112137830400000000000,
   R (3686757923) 1000000000000, R (31804139) 125000000000,
   [R (2393820493) 7812500000, R (207607355361) 1000000000000, R (17586341833) 125000000000, R (95373332411) 1000000000000, R (64827809439) 1000000000000, R (22192446781) 500000000000, R (1069247443) 50000000000, R (0) 1, R (18550495772481127546899414953291914907) 21778071482940061661655974875633165533184, R (17936009990373186364833365094775356321532641853) 2658455991569831745807614120560689152000000000000, R (228863661) 40000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   117, 18⟩

/-- The boxes of the strip P03. -/
def boxesP03 : List Box := [
  boxP03_000,
  boxP03_001
]

/-- The cover slabs of the strip P03. -/
def slabsP03 : List Slab := [
  ⟨R (9) 29, R (28) 87, [1]⟩,
  ⟨R (28) 87, R (1) 3, [0]⟩
]

end Erdos993Lean.Analytic.N44.Data
