import Erdos993Lean.Analytic.Atlas.Checker

/-!
# The n ≥ 44 strip atlas, piece 54 (band 30) (activity `[9/4, 7/3]`, `m ∈ [75/7, 80/7]`)

Generated by `LEAN/lanes/A21/scratch/gen_n.py` from the boxes `LEAN/r4x/atlas44_trial/band_30_9-4_7-3/box_*.json`
(lane R4X's trial strip, 7 boxes, of which the 5 meeting `[floor, cap]` and used by a cover chain are kept;
the saved `dual.alpha` already contains the constructor's `alpha_adjustment`).  Each box carries its dual's centre
`m0` (the box midpoint) and the checker's hints `N` (explicit cutoff: the Fourier tail applies from `N` on) and
`cm = ⌈m_l⌉`.  The strip is `[floor(n ≥ 44), floor(n ≥ 45)]`: from `k/(2 q(λ_hi))` with the n ≥ 44 rank
`k = 15` to the n ≥ 45 floor of the containing piece.  Caps of the piece: `D = 8/5`, `θ = 1`, rates
`1129/2500, 521/1250, 3869/10000, 657/2000, 1369/5000` (t = 0 rate of the parent band).
Tail base: the box's upper activity `lamBox b = qh/(1 − qh)`; no box is split (smallest margin (2) under the
checker's formula: 6.565e-04).  The slabs cover `[q(9/4), q(7/3)] × [75/7, 80/7]` (4 slabs).
-/

namespace Erdos993Lean.Analytic.N44.Data

open Erdos993Lean.Analytic.Atlas

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- r4x/atlas44_trial/band_30_9-4_7-3/box_000001.json -/
def boxP54_000 : Box :=
  ⟨R (363) 520, R (7) 10, R (75) 7, R (165) 14, R (45) 4,
   R (31391727157) 1000000000000, R (-4219500257) 500000000000,
   R (1960816571036705904936619023870665431799161771647) 10633823966279326983230456482242756608000000000000,
   R (17811989201) 1000000000000, R (4198427667) 1000000000000,
   [R (212082339921) 1000000000000, R (6779406889) 50000000000, R (43177192007) 500000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   120, 11⟩

/-- r4x/atlas44_trial/band_30_9-4_7-3/box_000002.json -/
def boxP54_001 : Box :=
  ⟨R (181) 260, R (363) 520, R (75) 7, R (165) 14, R (45) 4,
   R (31007149441) 1000000000000, R (-8146095663) 1000000000000,
   R (1934268238983397276997074242340529052918584756807) 10633823966279326983230456482242756608000000000000,
   R (8574495591) 500000000000, R (4202531733) 1000000000000,
   [R (53635402411) 250000000000, R (68448359117) 500000000000, R (17407637177) 200000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   119, 11⟩

/-- r4x/atlas44_trial/band_30_9-4_7-3/box_000004.json -/
def boxP54_002 : Box :=
  ⟨R (361) 520, R (181) 260, R (75) 7, R (165) 14, R (45) 4,
   R (15308410113) 500000000000, R (-3934543129) 500000000000,
   R (381667486597288956240378812704791552842459206381) 2126764793255865396646091296448551321600000000000,
   R (2063340803) 125000000000, R (2103068823) 500000000000,
   [R (54244868089) 250000000000, R (8635818553) 62500000000, R (87685711903) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   119, 11⟩

/-- r4x/atlas44_trial/band_30_9-4_7-3/box_000005.json -/
def boxP54_003 : Box :=
  ⟨R (9) 13, R (361) 520, R (45) 4, R (165) 14, R (645) 56,
   R (3022124051) 100000000000, R (-7606505701) 1000000000000,
   R (120314730174248421374603042246396253757099688449) 664613997892457936451903530140172288000000000000,
   R (2725986571) 200000000000, R (841839371) 200000000000,
   [R (43879584909) 200000000000, R (13941920963) 100000000000, R (44149440131) 500000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   118, 12⟩

/-- r4x/atlas44_trial/band_30_9-4_7-3/box_000006.json -/
def boxP54_004 : Box :=
  ⟨R (9) 13, R (361) 520, R (75) 7, R (45) 4, R (615) 56,
   R (3022124051) 100000000000, R (-7606505701) 1000000000000,
   R (114659033671590899344583959827762849029409001929) 664613997892457936451903530140172288000000000000,
   R (4534946657) 250000000000, R (841839371) 200000000000,
   [R (43879584909) 200000000000, R (13941920963) 100000000000, R (44149440131) 500000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1, R (0) 1],
   118, 11⟩

/-- The boxes of the strip P54. -/
def boxesP54 : List Box := [
  boxP54_000,
  boxP54_001,
  boxP54_002,
  boxP54_003,
  boxP54_004
]

/-- The cover slabs of the strip P54. -/
def slabsP54 : List Slab := [
  ⟨R (9) 13, R (361) 520, [4, 3]⟩,
  ⟨R (361) 520, R (181) 260, [2]⟩,
  ⟨R (181) 260, R (363) 520, [1]⟩,
  ⟨R (363) 520, R (7) 10, [0]⟩
]

end Erdos993Lean.Analytic.N44.Data
