import Erdos993Lean.Analytic.MGF.Pieces

/-!
# The MGF + two-sided atlas, rung 21, strip 07 (piece 7, activity `[13/20, 7/10]`, `m ∈ [17/2, 102/7]`)

Generated by `LEAN/lanes/A24/scratch/gen_mgf21.py` (lane A22's `gen_mgf.py` for rung 21) from lane M30's boxes `LEAN/atlas_mgf/rung_21/strip_07` (2 boxes, 1 slabs; SPEC v2 §4).
Boxes 0 are lane M30's boxes of the higher rung reused byte-identical (`rung_25/strip_07`, sha256 a63c015399bf…); the other 1 boxes are new on `[17/2, 68/7]`.
The piece is `piece21 7` (`MGF/N21/Pieces.lean`: `θ = 7/10`, `D = 7/5`, rates `459/1250, 139/400, 3253/10000, 177/625, 97/400`); the strip is
`[floor_21, floor_44] = [17/2, 102/7]`.  Each box carries its dual `(ν, c, α, β, γ, a, b, z)` centred at `m0` and its cutoff `N`.
The caps are lane M30's `rung_21/CAPS_N21.json` (sha256 `a11a7d149216850fff42b71aa1ab9feb82585274709a1f85f77956114212e47e`): `θ` and the tilts are Lean's N44 tables verbatim, `D` is
`D44` except lane O1R21's rows on pieces 24 (`21/20`) and 27 (`23/20`) (`MGF/N21/Pieces.lean`, `D21tab`); checked here per piece.
The box, COVER, SOURCE and VERIFIED files were checked against the rung-21 manifest
`LEAN/atlas_mgf/MANIFEST_RUNG_21.sha256` (sha256 of the manifest: `ef75ed56de6036b6fb10b9cbba0653325af517c1e099d5ab1554601e83e07b31`).
-/

namespace Erdos993Lean.Analytic.MGF.Data

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- strip_07/box_000000.json -/
def boxR21S07_000 : MBox :=
  ⟨R (13) 33, R (7) 17, R (68) 7, R (102) 7, R (85) 7,
   R (11074092737) 500000000000, R (1469505787) 31250000000,
   R (144767180196669875247149863839012750396033015159) 1329227995784915872903807060280344576000000000000,
   R (303374649) 1000000000000, R (232023477) 500000000000, R (1) 1, R (0) 1,
   [R (978972939111) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 112⟩

/-- strip_07/box_000001.json -/
def boxR21S07_001 : MBox :=
  ⟨R (13) 33, R (7) 17, R (17) 2, R (68) 7, R (255) 28,
   R (24892826833) 1000000000000, R (50458656189) 1000000000000,
   R (19200477223106392721682588518095535836612116337) 166153499473114484112975882535043072000000000000,
   R (522135839) 250000000000, R (143390173) 250000000000, R (1) 1, R (0) 1,
   [R (494502539701) 500000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 88⟩

/-- The boxes of the strip R21S07. -/
def boxesR21S07 : List MBox := [
  boxR21S07_000,
  boxR21S07_001
]

/-- The cover slabs of the strip R21S07. -/
def slabsR21S07 : List Atlas.Slab := [
  ⟨R (13) 33, R (7) 17, [1, 0]⟩
]

/-- The floor of `m` at `n ≥ 21` on piece 7: `17/2`. -/
def mloR21S07 : Rat := R (17) 2

end Erdos993Lean.Analytic.MGF.Data
