import Erdos993Lean.Analytic.MGF.Pieces

/-!
# The MGF + two-sided atlas, rung 21, strip 03 (piece 3, activity `[9/20, 1/2]`, `m ∈ [21/2, 18]`)

Generated by `LEAN/lanes/A24/scratch/gen_mgf21.py` (lane A22's `gen_mgf.py` for rung 21) from lane M30's boxes `LEAN/atlas_mgf/rung_21/strip_03` (2 boxes, 1 slabs; SPEC v2 §4).
Boxes 0 are lane M30's boxes of the higher rung reused byte-identical (`rung_25/strip_03`, sha256 a75962f1d953…); the other 1 boxes are new on `[21/2, 12]`.
The piece is `piece21 3` (`MGF/N21/Pieces.lean`: `θ = 1`, `D = 8/5`, rates `751/2500, 563/2000, 1333/5000, 291/1250, 1001/5000`); the strip is
`[floor_21, floor_44] = [21/2, 18]`.  Each box carries its dual `(ν, c, α, β, γ, a, b, z)` centred at `m0` and its cutoff `N`.
The caps are lane M30's `rung_21/CAPS_N21.json` (sha256 `a11a7d149216850fff42b71aa1ab9feb82585274709a1f85f77956114212e47e`): `θ` and the tilts are Lean's N44 tables verbatim, `D` is
`D44` except lane O1R21's rows on pieces 24 (`21/20`) and 27 (`23/20`) (`MGF/N21/Pieces.lean`, `D21tab`); checked here per piece.
The box, COVER, SOURCE and VERIFIED files were checked against the rung-21 manifest
`LEAN/atlas_mgf/MANIFEST_RUNG_21.sha256` (sha256 of the manifest: `ef75ed56de6036b6fb10b9cbba0653325af517c1e099d5ab1554601e83e07b31`).
-/

namespace Erdos993Lean.Analytic.MGF.Data

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- strip_03/box_000000.json -/
def boxR21S03_000 : MBox :=
  ⟨R (9) 29, R (1) 3, R (12) 1, R (18) 1, R (15) 1,
   R (305780363) 31250000000, R (967021697) 62500000000,
   R (5074918908009543286843279738210877995487682797) 42535295865117307932921825928971026432000000000,
   R (127858557) 31250000000, R (288742497) 1000000000000, R (1) 1, R (0) 1,
   [R (1012553891881) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 128⟩

/-- strip_03/box_000001.json -/
def boxR21S03_001 : MBox :=
  ⟨R (9) 29, R (1) 3, R (21) 2, R (12) 1, R (45) 4,
   R (14520796933) 1000000000000, R (21711120079) 1000000000000,
   R (365635983141734414850743252626288720962541660117) 2658455991569831745807614120560689152000000000000,
   R (2192881099) 500000000000, R (367567487) 500000000000, R (1) 1, R (0) 1,
   [R (41694831423) 40000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 104⟩

/-- The boxes of the strip R21S03. -/
def boxesR21S03 : List MBox := [
  boxR21S03_000,
  boxR21S03_001
]

/-- The cover slabs of the strip R21S03. -/
def slabsR21S03 : List Atlas.Slab := [
  ⟨R (9) 29, R (1) 3, [1, 0]⟩
]

/-- The floor of `m` at `n ≥ 21` on piece 3: `21/2`. -/
def mloR21S03 : Rat := R (21) 2

end Erdos993Lean.Analytic.MGF.Data
