import Erdos993Lean.Analytic.MGF.Pieces

/-!
# The MGF + two-sided atlas, rung 21, strip 06 (piece 6, activity `[3/5, 13/20]`, `m ∈ [231/26, 198/13]`)

Generated by `LEAN/lanes/A24/scratch/gen_mgf21.py` (lane A22's `gen_mgf.py` for rung 21) from lane M30's boxes `LEAN/atlas_mgf/rung_21/strip_06` (2 boxes, 1 slabs; SPEC v2 §4).
Boxes 0 are lane M30's boxes of the higher rung reused byte-identical (`rung_25/strip_06`, sha256 b7dffafb87bf…); the other 1 boxes are new on `[231/26, 132/13]`.
The piece is `piece21 6` (`MGF/N21/Pieces.lean`: `θ = 7/10`, `D = 7/5`, rates `3531/10000, 3343/10000, 3129/10000, 1363/5000, 146/625`); the strip is
`[floor_21, floor_44] = [231/26, 198/13]`.  Each box carries its dual `(ν, c, α, β, γ, a, b, z)` centred at `m0` and its cutoff `N`.
The caps are lane M30's `rung_21/CAPS_N21.json` (sha256 `a11a7d149216850fff42b71aa1ab9feb82585274709a1f85f77956114212e47e`): `θ` and the tilts are Lean's N44 tables verbatim, `D` is
`D44` except lane O1R21's rows on pieces 24 (`21/20`) and 27 (`23/20`) (`MGF/N21/Pieces.lean`, `D21tab`); checked here per piece.
The box, COVER, SOURCE and VERIFIED files were checked against the rung-21 manifest
`LEAN/atlas_mgf/MANIFEST_RUNG_21.sha256` (sha256 of the manifest: `ef75ed56de6036b6fb10b9cbba0653325af517c1e099d5ab1554601e83e07b31`).
-/

namespace Erdos993Lean.Analytic.MGF.Data

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- strip_06/box_000000.json -/
def boxR21S06_000 : MBox :=
  ⟨R (3) 8, R (13) 33, R (132) 13, R (198) 13, R (165) 13,
   R (16368438229) 1000000000000, R (34772689673) 1000000000000,
   R (230074451174133721790222081177065496622247292677) 2126764793255865396646091296448551321600000000000,
   R (1117044929) 500000000000, R (18637369) 62500000000, R (1) 1, R (0) 1,
   [R (995304611067) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 112⟩

/-- strip_06/box_000001.json -/
def boxR21S06_001 : MBox :=
  ⟨R (3) 8, R (13) 33, R (231) 26, R (132) 13, R (495) 52,
   R (22787593453) 1000000000000, R (8859851261) 200000000000,
   R (166332590238021726762582291040088814639902771941) 1329227995784915872903807060280344576000000000000,
   R (393369773) 200000000000, R (783169137) 1000000000000, R (1) 1, R (0) 1,
   [R (510131637771) 500000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 88⟩

/-- The boxes of the strip R21S06. -/
def boxesR21S06 : List MBox := [
  boxR21S06_000,
  boxR21S06_001
]

/-- The cover slabs of the strip R21S06. -/
def slabsR21S06 : List Atlas.Slab := [
  ⟨R (3) 8, R (13) 33, [1, 0]⟩
]

/-- The floor of `m` at `n ≥ 21` on piece 6: `231/26`. -/
def mloR21S06 : Rat := R (231) 26

end Erdos993Lean.Analytic.MGF.Data
