import Erdos993Lean.Analytic.MGF.Pieces

/-!
# The MGF + two-sided atlas, rung 21, strip 04 (piece 4, activity `[1/2, 11/20]`, `m ∈ [217/22, 186/11]`)

Generated by `LEAN/lanes/A24/scratch/gen_mgf21.py` (lane A22's `gen_mgf.py` for rung 21) from lane M30's boxes `LEAN/atlas_mgf/rung_21/strip_04` (2 boxes, 1 slabs; SPEC v2 §4).
Boxes 0 are lane M30's boxes of the higher rung reused byte-identical (`rung_25/strip_04`, sha256 04116987c726…); the other 1 boxes are new on `[217/22, 124/11]`.
The piece is `piece21 4` (`MGF/N21/Pieces.lean`: `θ = 1`, `D = 8/5`, rates `643/2000, 3013/10000, 2821/10000, 1231/5000, 1067/5000`); the strip is
`[floor_21, floor_44] = [217/22, 186/11]`.  Each box carries its dual `(ν, c, α, β, γ, a, b, z)` centred at `m0` and its cutoff `N`.
The caps are lane M30's `rung_21/CAPS_N21.json` (sha256 `a11a7d149216850fff42b71aa1ab9feb82585274709a1f85f77956114212e47e`): `θ` and the tilts are Lean's N44 tables verbatim, `D` is
`D44` except lane O1R21's rows on pieces 24 (`21/20`) and 27 (`23/20`) (`MGF/N21/Pieces.lean`, `D21tab`); checked here per piece.
The box, COVER, SOURCE and VERIFIED files were checked against the rung-21 manifest
`LEAN/atlas_mgf/MANIFEST_RUNG_21.sha256` (sha256 of the manifest: `ef75ed56de6036b6fb10b9cbba0653325af517c1e099d5ab1554601e83e07b31`).
-/

namespace Erdos993Lean.Analytic.MGF.Data

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- strip_04/box_000000.json -/
def boxR21S04_000 : MBox :=
  ⟨R (1) 3, R (11) 31, R (124) 11, R (186) 11, R (155) 11,
   R (5737725557) 500000000000, R (20662417801) 1000000000000,
   R (614942471782422405579830999645574030133967589107) 5316911983139663491615228241121378304000000000000,
   R (3651654723) 1000000000000, R (257364979) 1000000000000, R (1) 1, R (0) 1,
   [R (1009427350149) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 128⟩

/-- strip_04/box_000001.json -/
def boxR21S04_001 : MBox :=
  ⟨R (1) 3, R (11) 31, R (217) 22, R (124) 11, R (465) 44,
   R (3278902891) 200000000000, R (14067353359) 500000000000,
   R (70201481819327858919751662902384614925004671807) 531691198313966349161522824112137830400000000000,
   R (2467990627) 500000000000, R (161368621) 250000000000, R (1) 1, R (0) 1,
   [R (507934731583) 500000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 96⟩

/-- The boxes of the strip R21S04. -/
def boxesR21S04 : List MBox := [
  boxR21S04_000,
  boxR21S04_001
]

/-- The cover slabs of the strip R21S04. -/
def slabsR21S04 : List Atlas.Slab := [
  ⟨R (1) 3, R (11) 31, [1, 0]⟩
]

/-- The floor of `m` at `n ≥ 21` on piece 4: `217/22`. -/
def mloR21S04 : Rat := R (217) 22

end Erdos993Lean.Analytic.MGF.Data
