import Erdos993Lean.Analytic.MGF.Pieces

/-!
# The MGF + two-sided atlas, rung 21, strip 45 (piece 45, activity `[33/20, 17/10]`, `m ∈ [189/34, 405/34]`)

Generated by `LEAN/lanes/A24/scratch/gen_mgf21.py` (lane A22's `gen_mgf.py` for rung 21) from lane M30's boxes `LEAN/atlas_mgf/rung_21/strip_45` (4 boxes, 1 slabs; SPEC v2 §4).
Boxes 0, 1 are lane M30's boxes of the higher rung reused byte-identical (`rung_25/strip_45`, sha256 6ba5ce4e46cc…, 42c7edcc34da…); the other 2 boxes are new on `[189/34, 243/34]`.
The piece is `piece21 45` (`MGF/N21/Pieces.lean`: `θ = 19/20`, `D = 8/5`, rates `47/100, 2051/5000, 3807/10000, 202/625, 679/2500`); the strip is
`[floor_21, floor_44] = [189/34, 405/34]`.  Each box carries its dual `(ν, c, α, β, γ, a, b, z)` centred at `m0` and its cutoff `N`.
The caps are lane M30's `rung_21/CAPS_N21.json` (sha256 `a11a7d149216850fff42b71aa1ab9feb82585274709a1f85f77956114212e47e`): `θ` and the tilts are Lean's N44 tables verbatim, `D` is
`D44` except lane O1R21's rows on pieces 24 (`21/20`) and 27 (`23/20`) (`MGF/N21/Pieces.lean`, `D21tab`); checked here per piece.
The box, COVER, SOURCE and VERIFIED files were checked against the rung-21 manifest
`LEAN/atlas_mgf/MANIFEST_RUNG_21.sha256` (sha256 of the manifest: `ef75ed56de6036b6fb10b9cbba0653325af517c1e099d5ab1554601e83e07b31`).
-/

namespace Erdos993Lean.Analytic.MGF.Data

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- strip_45/box_000000.json -/
def boxR21S45_000 : MBox :=
  ⟨R (33) 53, R (17) 27, R (162) 17, R (405) 34, R (729) 68,
   R (1863879783) 100000000000, R (-35620595043) 1000000000000,
   R (626130081424824121592279936701959817053910896473) 5316911983139663491615228241121378304000000000000,
   R (156530767) 15625000000, R (1174774409) 1000000000000, R (0) 1, R (1) 1,
   [R (412715577959) 500000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 48⟩

/-- strip_45/box_000001.json -/
def boxR21S45_001 : MBox :=
  ⟨R (33) 53, R (17) 27, R (243) 34, R (162) 17, R (567) 68,
   R (21106555889) 500000000000, R (-34614322929) 500000000000,
   R (960788861859407219570652575361310240872934725093) 5316911983139663491615228241121378304000000000000,
   R (801733981) 100000000000, R (2396017139) 1000000000000, R (0) 1, R (1) 1,
   [R (879700860109) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 40⟩

/-- strip_45/box_000002.json -/
def boxR21S45_002 : MBox :=
  ⟨R (33) 53, R (17) 27, R (108) 17, R (243) 34, R (27) 4,
   R (5726318847) 125000000000, R (-74592398329) 1000000000000,
   R (1812437555456709694570001173737351283771235419293) 10633823966279326983230456482242756608000000000000,
   R (7699195551) 500000000000, R (637141277) 250000000000, R (0) 1, R (1) 1,
   [R (836023560433) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 32⟩

/-- strip_45/box_000003.json -/
def boxR21S45_003 : MBox :=
  ⟨R (33) 53, R (17) 27, R (189) 34, R (108) 17, R (405) 68,
   R (73246093401) 1000000000000, R (-100109075217) 1000000000000,
   R (584894227389437600856328092928679210465913159787) 2658455991569831745807614120560689152000000000000,
   R (11059510933) 1000000000000, R (1923659113) 500000000000, R (0) 1, R (1) 1,
   [R (851151599249) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 28⟩

/-- The boxes of the strip R21S45. -/
def boxesR21S45 : List MBox := [
  boxR21S45_000,
  boxR21S45_001,
  boxR21S45_002,
  boxR21S45_003
]

/-- The cover slabs of the strip R21S45. -/
def slabsR21S45 : List Atlas.Slab := [
  ⟨R (33) 53, R (17) 27, [3, 2, 1, 0]⟩
]

/-- The floor of `m` at `n ≥ 21` on piece 45: `189/34`. -/
def mloR21S45 : Rat := R (189) 34

end Erdos993Lean.Analytic.MGF.Data
