import Erdos993Lean.Analytic.MGF.Pieces

/-!
# The MGF + two-sided atlas, rung 21, strip 13 (piece 13, activity `[43/50, 87/100]`, `m ∈ [1309/174, 374/29]`)

Generated by `LEAN/lanes/A24/scratch/gen_mgf21.py` (lane A22's `gen_mgf.py` for rung 21) from lane M30's boxes `LEAN/atlas_mgf/rung_21/strip_13` (5 boxes, 1 slabs; SPEC v2 §4).
Boxes 0, 1, 2 are lane M30's boxes of the higher rung reused byte-identical (`rung_25/strip_13`, sha256 b95f465ed07e…, d23c6257a74a…, d6d3b914ef2b…); the other 2 boxes are new on `[1309/174, 748/87]`.
The piece is `piece21 13` (`MGF/N21/Pieces.lean`: `θ = 3/5`, `D = 6/5`, rates `4129/10000, 3871/10000, 3623/10000, 5/16, 267/1000`); the strip is
`[floor_21, floor_44] = [1309/174, 374/29]`.  Each box carries its dual `(ν, c, α, β, γ, a, b, z)` centred at `m0` and its cutoff `N`.
The caps are lane M30's `rung_21/CAPS_N21.json` (sha256 `a11a7d149216850fff42b71aa1ab9feb82585274709a1f85f77956114212e47e`): `θ` and the tilts are Lean's N44 tables verbatim, `D` is
`D44` except lane O1R21's rows on pieces 24 (`21/20`) and 27 (`23/20`) (`MGF/N21/Pieces.lean`, `D21tab`); checked here per piece.
The box, COVER, SOURCE and VERIFIED files were checked against the rung-21 manifest
`LEAN/atlas_mgf/MANIFEST_RUNG_21.sha256` (sha256 of the manifest: `ef75ed56de6036b6fb10b9cbba0653325af517c1e099d5ab1554601e83e07b31`).
-/

namespace Erdos993Lean.Analytic.MGF.Data

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- strip_13/box_000000.json -/
def boxR21S13_000 : MBox :=
  ⟨R (43) 93, R (87) 187, R (935) 87, R (374) 29, R (2057) 174,
   R (16698718651) 1000000000000, R (7018514537) 250000000000,
   R (253546067862010365784366141841243835958502192821) 4253529586511730793292182592897102643200000000000,
   R (0) 1, R (349885673) 500000000000, R (1) 1, R (107365112773) 250000000000,
   [R (458980986831) 500000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 52⟩

/-- strip_13/box_000001.json -/
def boxR21S13_001 : MBox :=
  ⟨R (43) 93, R (87) 187, R (561) 58, R (935) 87, R (3553) 348,
   R (10076951303) 500000000000, R (23639762983) 1000000000000,
   R (5721970720633094764846285071373939687220604406523) 85070591730234615865843651857942052864000000000000,
   R (151015563) 500000000000, R (822078699) 1000000000000, R (1) 1, R (582454298853) 1000000000000,
   [R (187098450463) 200000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 48⟩

/-- strip_13/box_000002.json -/
def boxR21S13_002 : MBox :=
  ⟨R (43) 93, R (87) 187, R (748) 87, R (561) 58, R (3179) 348,
   R (25638799673) 1000000000000, R (17773593611) 500000000000,
   R (3259298459203597481429068341495528925014919398249) 42535295865117307932921825928971026432000000000000,
   R (-122462413) 100000000000, R (71847809) 100000000000, R (1) 1, R (228990248937) 500000000000,
   [R (967678845973) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 88⟩

/-- strip_13/box_000003.json -/
def boxR21S13_003 : MBox :=
  ⟨R (43) 93, R (87) 187, R (935) 116, R (748) 87, R (5797) 696,
   R (7293736723) 250000000000, R (3522845337) 100000000000,
   R (3517454630434686128616462121202619300266650788269) 42535295865117307932921825928971026432000000000000,
   R (-2782899321) 1000000000000, R (14139401) 31250000000, R (1) 1, R (33087773499) 62500000000,
   [R (1011034081407) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 80⟩

/-- strip_13/box_000004.json -/
def boxR21S13_004 : MBox :=
  ⟨R (43) 93, R (87) 187, R (1309) 174, R (935) 116, R (187) 24,
   R (1957762131) 50000000000, R (3267378771) 100000000000,
   R (414967568257385007645365172813294966770025935551) 4253529586511730793292182592897102643200000000000,
   R (-3461783551) 500000000000, R (2044033) 100000000000, R (1) 1, R (311362783157) 500000000000,
   [R (1080349456977) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 144⟩

/-- The boxes of the strip R21S13. -/
def boxesR21S13 : List MBox := [
  boxR21S13_000,
  boxR21S13_001,
  boxR21S13_002,
  boxR21S13_003,
  boxR21S13_004
]

/-- The cover slabs of the strip R21S13. -/
def slabsR21S13 : List Atlas.Slab := [
  ⟨R (43) 93, R (87) 187, [4, 3, 2, 1, 0]⟩
]

/-- The floor of `m` at `n ≥ 21` on piece 13: `1309/174`. -/
def mloR21S13 : Rat := R (1309) 174

end Erdos993Lean.Analytic.MGF.Data
