import Erdos993Lean.Analytic.MGF.Pieces

/-!
# The MGF + two-sided atlas, rung 21, strip 05 (piece 5, activity `[11/20, 3/5]`, `m ∈ [28/3, 16]`)

Generated by `LEAN/lanes/A24/scratch/gen_mgf21.py` (lane A22's `gen_mgf.py` for rung 21) from lane M30's boxes `LEAN/atlas_mgf/rung_21/strip_05` (2 boxes, 1 slabs; SPEC v2 §4).
Boxes 0 are lane M30's boxes of the higher rung reused byte-identical (`rung_25/strip_05`, sha256 242c59b96ddb…); the other 1 boxes are new on `[28/3, 32/3]`.
The piece is `piece21 5` (`MGF/N21/Pieces.lean`: `θ = 1`, `D = 8/5`, rates `339/1000, 1589/5000, 119/400, 1297/5000, 139/625`); the strip is
`[floor_21, floor_44] = [28/3, 16]`.  Each box carries its dual `(ν, c, α, β, γ, a, b, z)` centred at `m0` and its cutoff `N`.
The caps are lane M30's `rung_21/CAPS_N21.json` (sha256 `a11a7d149216850fff42b71aa1ab9feb82585274709a1f85f77956114212e47e`): `θ` and the tilts are Lean's N44 tables verbatim, `D` is
`D44` except lane O1R21's rows on pieces 24 (`21/20`) and 27 (`23/20`) (`MGF/N21/Pieces.lean`, `D21tab`); checked here per piece.
The box, COVER, SOURCE and VERIFIED files were checked against the rung-21 manifest
`LEAN/atlas_mgf/MANIFEST_RUNG_21.sha256` (sha256 of the manifest: `ef75ed56de6036b6fb10b9cbba0653325af517c1e099d5ab1554601e83e07b31`).
-/

namespace Erdos993Lean.Analytic.MGF.Data

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- strip_05/box_000000.json -/
def boxR21S05_000 : MBox :=
  ⟨R (11) 31, R (3) 8, R (32) 3, R (16) 1, R (40) 3,
   R (6285747603) 500000000000, R (1278427031) 50000000000,
   R (67833636867621100683622800798706731808383675061) 664613997892457936451903530140172288000000000000,
   R (1607423913) 500000000000, R (92902903) 500000000000, R (1) 1, R (0) 1,
   [R (1000593983973) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 120⟩

/-- strip_05/box_000001.json -/
def boxR21S05_001 : MBox :=
  ⟨R (11) 31, R (3) 8, R (28) 3, R (32) 3, R (10) 1,
   R (21709090087) 1000000000000, R (4819094303) 125000000000,
   R (146356565047463244431223346187234757330903333451) 1063382396627932698323045648224275660800000000000,
   R (220362521) 125000000000, R (156941101) 250000000000, R (1) 1, R (0) 1,
   [R (1049249914849) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 88⟩

/-- The boxes of the strip R21S05. -/
def boxesR21S05 : List MBox := [
  boxR21S05_000,
  boxR21S05_001
]

/-- The cover slabs of the strip R21S05. -/
def slabsR21S05 : List Atlas.Slab := [
  ⟨R (11) 31, R (3) 8, [1, 0]⟩
]

/-- The floor of `m` at `n ≥ 21` on piece 5: `28/3`. -/
def mloR21S05 : Rat := R (28) 3

end Erdos993Lean.Analytic.MGF.Data
