import Erdos993Lean.Analytic.MGF.Pieces

/-!
# The MGF + two-sided atlas, rung 21, strip 14 (piece 14, activity `[87/100, 22/25]`, `m ∈ [329/44, 141/11]`)

Generated by `LEAN/lanes/A24/scratch/gen_mgf21.py` (lane A22's `gen_mgf.py` for rung 21) from lane M30's boxes `LEAN/atlas_mgf/rung_21/strip_14` (5 boxes, 1 slabs; SPEC v2 §4).
Boxes 0, 1, 2 are lane M30's boxes of the higher rung reused byte-identical (`rung_25/strip_14`, sha256 8f85e6e6674b…, 202f86f1fad7…, a83853985736…); the other 2 boxes are new on `[329/44, 94/11]`.
The piece is `piece21 14` (`MGF/N21/Pieces.lean`: `θ = 3/5`, `D = 6/5`, rates `171/400, 3871/10000, 3623/10000, 5/16, 267/1000`); the strip is
`[floor_21, floor_44] = [329/44, 141/11]`.  Each box carries its dual `(ν, c, α, β, γ, a, b, z)` centred at `m0` and its cutoff `N`.
The caps are lane M30's `rung_21/CAPS_N21.json` (sha256 `a11a7d149216850fff42b71aa1ab9feb82585274709a1f85f77956114212e47e`): `θ` and the tilts are Lean's N44 tables verbatim, `D` is
`D44` except lane O1R21's rows on pieces 24 (`21/20`) and 27 (`23/20`) (`MGF/N21/Pieces.lean`, `D21tab`); checked here per piece.
The box, COVER, SOURCE and VERIFIED files were checked against the rung-21 manifest
`LEAN/atlas_mgf/MANIFEST_RUNG_21.sha256` (sha256 of the manifest: `ef75ed56de6036b6fb10b9cbba0653325af517c1e099d5ab1554601e83e07b31`).
-/

namespace Erdos993Lean.Analytic.MGF.Data

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- strip_14/box_000000.json -/
def boxR21S14_000 : MBox :=
  ⟨R (87) 187, R (22) 47, R (235) 22, R (141) 11, R (47) 4,
   R (16602638631) 1000000000000, R (11866816333) 500000000000,
   R (4840030072997276179726226438678018520497452894669) 85070591730234615865843651857942052864000000000000,
   R (0) 1, R (633633359) 1000000000000, R (1) 1, R (108556007299) 200000000000,
   [R (929833716261) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 104⟩

/-- strip_14/box_000001.json -/
def boxR21S14_001 : MBox :=
  ⟨R (87) 187, R (22) 47, R (423) 44, R (235) 22, R (893) 88,
   R (643462397) 31250000000, R (23507599093) 1000000000000,
   R (5718018998060217412087541492576211133304385150409) 85070591730234615865843651857942052864000000000000,
   R (27446611) 500000000000, R (17694893) 20000000000, R (1) 1, R (148871734291) 250000000000,
   [R (932214457911) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 48⟩

/-- strip_14/box_000002.json -/
def boxR21S14_002 : MBox :=
  ⟨R (87) 187, R (22) 47, R (94) 11, R (423) 44, R (799) 88,
   R (24464912547) 1000000000000, R (15737952413) 500000000000,
   R (3130526156347776705768657367129756219605871159617) 42535295865117307932921825928971026432000000000000,
   R (-171585997) 500000000000, R (829291597) 1000000000000, R (1) 1, R (10311780737) 20000000000,
   [R (476664959209) 500000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 88⟩

/-- strip_14/box_000003.json -/
def boxR21S14_003 : MBox :=
  ⟨R (87) 187, R (22) 47, R (705) 88, R (94) 11, R (1457) 176,
   R (6142354971) 200000000000, R (8065651373) 250000000000,
   R (7305723110800321136913689668675455767140489971891) 85070591730234615865843651857942052864000000000000,
   R (-327003791) 125000000000, R (754312057) 1000000000000, R (1) 1, R (568892361181) 1000000000000,
   [R (993740492399) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 80⟩

/-- strip_14/box_000004.json -/
def boxR21S14_004 : MBox :=
  ⟨R (87) 187, R (22) 47, R (329) 44, R (705) 88, R (1363) 176,
   R (1500032277) 40000000000, R (5579828993) 200000000000,
   R (8043929587782464216143007518023580383776227116861) 85070591730234615865843651857942052864000000000000,
   R (-5858187761) 1000000000000, R (3446401) 25000000000, R (1) 1, R (664467017107) 1000000000000,
   [R (1067052269117) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 144⟩

/-- The boxes of the strip R21S14. -/
def boxesR21S14 : List MBox := [
  boxR21S14_000,
  boxR21S14_001,
  boxR21S14_002,
  boxR21S14_003,
  boxR21S14_004
]

/-- The cover slabs of the strip R21S14. -/
def slabsR21S14 : List Atlas.Slab := [
  ⟨R (87) 187, R (22) 47, [4, 3, 2, 1, 0]⟩
]

/-- The floor of `m` at `n ≥ 21` on piece 14: `329/44`. -/
def mloR21S14 : Rat := R (329) 44

end Erdos993Lean.Analytic.MGF.Data
