import Erdos993Lean.Analytic.MGF.Pieces

/-!
# The MGF + two-sided atlas, rung 21, strip 46 (piece 46, activity `[17/10, 7/4]`, `m ∈ [11/2, 165/14]`)

Generated by `LEAN/lanes/A24/scratch/gen_mgf21.py` (lane A22's `gen_mgf.py` for rung 21) from lane M30's boxes `LEAN/atlas_mgf/rung_21/strip_46` (4 boxes, 1 slabs; SPEC v2 §4).
Boxes 0, 1 are lane M30's boxes of the higher rung reused byte-identical (`rung_25/strip_46`, sha256 5942f894bad1…, bc15ec262522…); the other 2 boxes are new on `[11/2, 99/14]`.
The piece is `piece21 46` (`MGF/N21/Pieces.lean`: `θ = 19/20`, `D = 8/5`, rates `941/2000, 2051/5000, 3807/10000, 202/625, 679/2500`); the strip is
`[floor_21, floor_44] = [11/2, 165/14]`.  Each box carries its dual `(ν, c, α, β, γ, a, b, z)` centred at `m0` and its cutoff `N`.
The caps are lane M30's `rung_21/CAPS_N21.json` (sha256 `a11a7d149216850fff42b71aa1ab9feb82585274709a1f85f77956114212e47e`): `θ` and the tilts are Lean's N44 tables verbatim, `D` is
`D44` except lane O1R21's rows on pieces 24 (`21/20`) and 27 (`23/20`) (`MGF/N21/Pieces.lean`, `D21tab`); checked here per piece.
The box, COVER, SOURCE and VERIFIED files were checked against the rung-21 manifest
`LEAN/atlas_mgf/MANIFEST_RUNG_21.sha256` (sha256 of the manifest: `ef75ed56de6036b6fb10b9cbba0653325af517c1e099d5ab1554601e83e07b31`).
-/

namespace Erdos993Lean.Analytic.MGF.Data

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- strip_46/box_000000.json -/
def boxR21S46_000 : MBox :=
  ⟨R (17) 27, R (7) 11, R (66) 7, R (165) 14, R (297) 28,
   R (3753767447) 200000000000, R (-17608468903) 500000000000,
   R (16513040496470780003328500702266499702590248113) 132922799578491587290380706028034457600000000000,
   R (2587831713) 250000000000, R (1256146449) 1000000000000, R (0) 1, R (1) 1,
   [R (822561241887) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 48⟩

/-- strip_46/box_000001.json -/
def boxR21S46_001 : MBox :=
  ⟨R (17) 27, R (7) 11, R (99) 14, R (66) 7, R (33) 4,
   R (10166727503) 250000000000, R (-32524865799) 500000000000,
   R (1945755862110545503783909992474420745670871799829) 10633823966279326983230456482242756608000000000000,
   R (2495388687) 250000000000, R (2405504193) 1000000000000, R (0) 1, R (1) 1,
   [R (884250602261) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 40⟩

/-- strip_46/box_000002.json -/
def boxR21S46_002 : MBox :=
  ⟨R (17) 27, R (7) 11, R (44) 7, R (99) 14, R (187) 28,
   R (44976960009) 1000000000000, R (-35549335659) 500000000000,
   R (1836092723062246216513169162551987544967681772469) 10633823966279326983230456482242756608000000000000,
   R (17476795163) 1000000000000, R (164228689) 62500000000, R (0) 1, R (1) 1,
   [R (103580357389) 125000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 32⟩

/-- strip_46/box_000003.json -/
def boxR21S46_003 : MBox :=
  ⟨R (17) 27, R (7) 11, R (11) 2, R (44) 7, R (165) 28,
   R (581984659) 8000000000, R (-24135032361) 250000000000,
   R (2395310399483720589144008915211459416323394539063) 10633823966279326983230456482242756608000000000000,
   R (1373131751) 100000000000, R (499698713) 125000000000, R (0) 1, R (1) 1,
   [R (105372857937) 125000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 28⟩

/-- The boxes of the strip R21S46. -/
def boxesR21S46 : List MBox := [
  boxR21S46_000,
  boxR21S46_001,
  boxR21S46_002,
  boxR21S46_003
]

/-- The cover slabs of the strip R21S46. -/
def slabsR21S46 : List Atlas.Slab := [
  ⟨R (17) 27, R (7) 11, [3, 2, 1, 0]⟩
]

/-- The floor of `m` at `n ≥ 21` on piece 46: `11/2`. -/
def mloR21S46 : Rat := R (11) 2

end Erdos993Lean.Analytic.MGF.Data
