import Erdos993Lean.Analytic.MGF.Pieces

/-!
# The MGF + two-sided atlas, rung 21, strip 01 (piece 1, activity `[9/25, 2/5]`, `m ∈ [49/4, 21]`)

Generated by `LEAN/lanes/A24/scratch/gen_mgf21.py` (lane A22's `gen_mgf.py` for rung 21) from lane M30's boxes `LEAN/atlas_mgf/rung_21/strip_01` (2 boxes, 1 slabs; SPEC v2 §4).
Boxes 0 are lane M30's boxes of the higher rung reused byte-identical (`rung_25/strip_01`, sha256 1f889d4fb94b…); the other 1 boxes are new on `[49/4, 14]`.
The piece is `piece21 1` (`MGF/N21/Pieces.lean`: `θ = 1`, `D = 8/5`, rates `1309/5000, 613/2500, 2327/10000, 509/2500, 439/2500`); the strip is
`[floor_21, floor_44] = [49/4, 21]`.  Each box carries its dual `(ν, c, α, β, γ, a, b, z)` centred at `m0` and its cutoff `N`.
The caps are lane M30's `rung_21/CAPS_N21.json` (sha256 `a11a7d149216850fff42b71aa1ab9feb82585274709a1f85f77956114212e47e`): `θ` and the tilts are Lean's N44 tables verbatim, `D` is
`D44` except lane O1R21's rows on pieces 24 (`21/20`) and 27 (`23/20`) (`MGF/N21/Pieces.lean`, `D21tab`); checked here per piece.
The box, COVER, SOURCE and VERIFIED files were checked against the rung-21 manifest
`LEAN/atlas_mgf/MANIFEST_RUNG_21.sha256` (sha256 of the manifest: `ef75ed56de6036b6fb10b9cbba0653325af517c1e099d5ab1554601e83e07b31`).
-/

namespace Erdos993Lean.Analytic.MGF.Data

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- strip_01/box_000000.json -/
def boxR21S01_000 : MBox :=
  ⟨R (9) 34, R (2) 7, R (14) 1, R (21) 1, R (35) 2,
   R (6562074947) 1000000000000, R (3378862473) 500000000000,
   R (30223037749748316633152025799403172219912683437) 265845599156983174580761412056068915200000000000,
   R (85390943) 50000000000, R (58944109) 200000000000, R (1) 1, R (0) 1,
   [R (534016867681) 500000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 152⟩

/-- strip_01/box_000001.json -/
def boxR21S01_001 : MBox :=
  ⟨R (9) 34, R (2) 7, R (49) 4, R (14) 1, R (105) 8,
   R (4783079569) 500000000000, R (2030644887) 200000000000,
   R (286525557668469665487156880253816257658526705407) 2126764793255865396646091296448551321600000000000,
   R (9051049) 5000000000, R (718474391) 1000000000000, R (1) 1, R (0) 1,
   [R (1093016005331) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 60⟩

/-- The boxes of the strip R21S01. -/
def boxesR21S01 : List MBox := [
  boxR21S01_000,
  boxR21S01_001
]

/-- The cover slabs of the strip R21S01. -/
def slabsR21S01 : List Atlas.Slab := [
  ⟨R (9) 34, R (2) 7, [1, 0]⟩
]

/-- The floor of `m` at `n ≥ 21` on piece 1: `49/4`. -/
def mloR21S01 : Rat := R (49) 4

end Erdos993Lean.Analytic.MGF.Data
