import Erdos993Lean.Analytic.MGF.Pieces

/-!
# The MGF + two-sided atlas, rung 21, strip 41 (piece 41, activity `[57/40, 29/20]`, `m ∈ [343/58, 343/29]`)

Generated by `LEAN/lanes/A24/scratch/gen_mgf21.py` (lane A22's `gen_mgf.py` for rung 21) from lane M30's boxes `LEAN/atlas_mgf/rung_21/strip_41` (4 boxes, 1 slabs; SPEC v2 §4).
Boxes 0, 1, 2 are lane M30's boxes of the higher rung reused byte-identical (`rung_25/strip_41`, sha256 470cdfb33839…, cdd9f831f67a…, d5bc71cfa740…); the other 1 boxes are new on `[343/58, 196/29]`.
The piece is `piece21 41` (`MGF/N21/Pieces.lean`: `θ = 7/10`, `D = 7/5`, rates `4481/10000, 521/1250, 3869/10000, 207/625, 701/2500`); the strip is
`[floor_21, floor_44] = [343/58, 343/29]`.  Each box carries its dual `(ν, c, α, β, γ, a, b, z)` centred at `m0` and its cutoff `N`.
The caps are lane M30's `rung_21/CAPS_N21.json` (sha256 `a11a7d149216850fff42b71aa1ab9feb82585274709a1f85f77956114212e47e`): `θ` and the tilts are Lean's N44 tables verbatim, `D` is
`D44` except lane O1R21's rows on pieces 24 (`21/20`) and 27 (`23/20`) (`MGF/N21/Pieces.lean`, `D21tab`); checked here per piece.
The box, COVER, SOURCE and VERIFIED files were checked against the rung-21 manifest
`LEAN/atlas_mgf/MANIFEST_RUNG_21.sha256` (sha256 of the manifest: `ef75ed56de6036b6fb10b9cbba0653325af517c1e099d5ab1554601e83e07b31`).
-/

namespace Erdos993Lean.Analytic.MGF.Data

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- strip_41/box_000000.json -/
def boxR21S41_000 : MBox :=
  ⟨R (57) 97, R (29) 49, R (1127) 116, R (343) 29, R (2499) 232,
   R (8549570003) 500000000000, R (-33403025679) 1000000000000,
   R (473606392970786069642976993416938071735639803493) 5316911983139663491615228241121378304000000000000,
   R (6379639843) 1000000000000, R (525556577) 500000000000, R (95714504039) 500000000000, R (1) 1,
   [R (849972742467) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 48⟩

/-- strip_41/box_000001.json -/
def boxR21S41_001 : MBox :=
  ⟨R (57) 97, R (29) 49, R (441) 58, R (1127) 116, R (2009) 232,
   R (9856418981) 250000000000, R (-37056103097) 500000000000,
   R (2952926458869041597506657216631024346491565740213) 21267647932558653966460912964485513216000000000000,
   R (1667354233) 500000000000, R (1073385693) 500000000000, R (0) 1, R (1) 1,
   [R (83846637951) 100000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 40⟩

/-- strip_41/box_000002.json -/
def boxR21S41_002 : MBox :=
  ⟨R (57) 97, R (29) 49, R (196) 29, R (441) 58, R (833) 116,
   R (25476752729) 500000000000, R (-18186074591) 200000000000,
   R (3241847267679942940458379479424028110444996410601) 21267647932558653966460912964485513216000000000000,
   R (2610594597) 1000000000000, R (549807353) 250000000000, R (0) 1, R (1) 1,
   [R (88157318701) 100000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 36⟩

/-- strip_41/box_000003.json -/
def boxR21S41_003 : MBox :=
  ⟨R (57) 97, R (29) 49, R (343) 58, R (196) 29, R (735) 116,
   R (63768473863) 1000000000000, R (-20898694917) 200000000000,
   R (3610057977547001393371294908838792796182018008361) 21267647932558653966460912964485513216000000000000,
   R (1463131029) 1000000000000, R (1276550403) 500000000000, R (0) 1, R (1) 1,
   [R (893116258339) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 32⟩

/-- The boxes of the strip R21S41. -/
def boxesR21S41 : List MBox := [
  boxR21S41_000,
  boxR21S41_001,
  boxR21S41_002,
  boxR21S41_003
]

/-- The cover slabs of the strip R21S41. -/
def slabsR21S41 : List Atlas.Slab := [
  ⟨R (57) 97, R (29) 49, [3, 2, 1, 0]⟩
]

/-- The floor of `m` at `n ≥ 21` on piece 41: `343/58`. -/
def mloR21S41 : Rat := R (343) 58

end Erdos993Lean.Analytic.MGF.Data
