import Erdos993Lean.Analytic.MGF.Pieces

/-!
# The MGF + two-sided atlas, rung 21, strip 00 (piece 0, activity `[1/3, 9/25]`, `m ∈ [119/9, 68/3]`)

Generated by `LEAN/lanes/A24/scratch/gen_mgf21.py` (lane A22's `gen_mgf.py` for rung 21) from lane M30's boxes `LEAN/atlas_mgf/rung_21/strip_00` (2 boxes, 1 slabs; SPEC v2 §4).
Boxes 0 are lane M30's boxes of the higher rung reused byte-identical (`rung_25/strip_00`, sha256 cf470a5f9c24…); the other 1 boxes are new on `[119/9, 136/9]`.
The piece is `piece21 0` (`MGF/N21/Pieces.lean`: `θ = 1`, `D = 8/5`, rates `619/2500, 2353/10000, 551/2500, 489/2500, 169/1000`); the strip is
`[floor_21, floor_44] = [119/9, 68/3]`.  Each box carries its dual `(ν, c, α, β, γ, a, b, z)` centred at `m0` and its cutoff `N`.
The caps are lane M30's `rung_21/CAPS_N21.json` (sha256 `a11a7d149216850fff42b71aa1ab9feb82585274709a1f85f77956114212e47e`): `θ` and the tilts are Lean's N44 tables verbatim, `D` is
`D44` except lane O1R21's rows on pieces 24 (`21/20`) and 27 (`23/20`) (`MGF/N21/Pieces.lean`, `D21tab`); checked here per piece.
The box, COVER, SOURCE and VERIFIED files were checked against the rung-21 manifest
`LEAN/atlas_mgf/MANIFEST_RUNG_21.sha256` (sha256 of the manifest: `ef75ed56de6036b6fb10b9cbba0653325af517c1e099d5ab1554601e83e07b31`).
-/

namespace Erdos993Lean.Analytic.MGF.Data

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- strip_00/box_000000.json -/
def boxR21S00_000 : MBox :=
  ⟨R (1) 4, R (9) 34, R (136) 9, R (68) 3, R (170) 9,
   R (1785611821) 500000000000, R (2737830477) 1000000000000,
   R (3466915301062740939745555408840993683510045336329) 42535295865117307932921825928971026432000000000000,
   R (673599087) 500000000000, R (90723309) 500000000000, R (1) 1, R (0) 1,
   [R (52469604537) 50000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 160⟩

/-- strip_00/box_000001.json -/
def boxR21S00_001 : MBox :=
  ⟨R (1) 4, R (9) 34, R (119) 9, R (136) 9, R (85) 6,
   R (1652787501) 200000000000, R (6628996391) 1000000000000,
   R (722117521432483281493514552390624404592083057433) 5316911983139663491615228241121378304000000000000,
   R (533174513) 250000000000, R (178915767) 250000000000, R (1) 1, R (0) 1,
   [R (1090714587521) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 64⟩

/-- The boxes of the strip R21S00. -/
def boxesR21S00 : List MBox := [
  boxR21S00_000,
  boxR21S00_001
]

/-- The cover slabs of the strip R21S00. -/
def slabsR21S00 : List Atlas.Slab := [
  ⟨R (1) 4, R (9) 34, [1, 0]⟩
]

/-- The floor of `m` at `n ≥ 21` on piece 0: `119/9`. -/
def mloR21S00 : Rat := R (119) 9

end Erdos993Lean.Analytic.MGF.Data
