import Erdos993Lean.Analytic.MGF.Pieces

/-!
# The MGF + two-sided atlas, rung 21, strip 02 (piece 2, activity `[2/5, 9/20]`, `m ∈ [203/18, 58/3]`)

Generated by `LEAN/lanes/A24/scratch/gen_mgf21.py` (lane A22's `gen_mgf.py` for rung 21) from lane M30's boxes `LEAN/atlas_mgf/rung_21/strip_02` (2 boxes, 1 slabs; SPEC v2 §4).
Boxes 0 are lane M30's boxes of the higher rung reused byte-identical (`rung_25/strip_02`, sha256 0680cc0bb033…); the other 1 boxes are new on `[203/18, 116/9]`.
The piece is `piece21 2` (`MGF/N21/Pieces.lean`: `θ = 1`, `D = 8/5`, rates `2793/10000, 2617/10000, 2451/10000, 271/1250, 467/2500`); the strip is
`[floor_21, floor_44] = [203/18, 58/3]`.  Each box carries its dual `(ν, c, α, β, γ, a, b, z)` centred at `m0` and its cutoff `N`.
The caps are lane M30's `rung_21/CAPS_N21.json` (sha256 `a11a7d149216850fff42b71aa1ab9feb82585274709a1f85f77956114212e47e`): `θ` and the tilts are Lean's N44 tables verbatim, `D` is
`D44` except lane O1R21's rows on pieces 24 (`21/20`) and 27 (`23/20`) (`MGF/N21/Pieces.lean`, `D21tab`); checked here per piece.
The box, COVER, SOURCE and VERIFIED files were checked against the rung-21 manifest
`LEAN/atlas_mgf/MANIFEST_RUNG_21.sha256` (sha256 of the manifest: `ef75ed56de6036b6fb10b9cbba0653325af517c1e099d5ab1554601e83e07b31`).
-/

namespace Erdos993Lean.Analytic.MGF.Data

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- strip_02/box_000000.json -/
def boxR21S02_000 : MBox :=
  ⟨R (2) 7, R (9) 29, R (116) 9, R (58) 3, R (145) 9,
   R (8609676201) 1000000000000, R (5435199361) 500000000000,
   R (652877632728407356654007231507488251889917367249) 5316911983139663491615228241121378304000000000000,
   R (3557288301) 1000000000000, R (158627269) 500000000000, R (1) 1, R (0) 1,
   [R (1035007683599) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 144⟩

/-- strip_02/box_000001.json -/
def boxR21S02_001 : MBox :=
  ⟨R (2) 7, R (9) 29, R (203) 18, R (116) 9, R (145) 12,
   R (3414369763) 250000000000, R (1701846247) 100000000000,
   R (794231723812293595485685792157116483523037902689) 5316911983139663491615228241121378304000000000000,
   R (346867871) 125000000000, R (851448893) 1000000000000, R (1) 1, R (0) 1,
   [R (271572674643) 250000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 56⟩

/-- The boxes of the strip R21S02. -/
def boxesR21S02 : List MBox := [
  boxR21S02_000,
  boxR21S02_001
]

/-- The cover slabs of the strip R21S02. -/
def slabsR21S02 : List Atlas.Slab := [
  ⟨R (2) 7, R (9) 29, [1, 0]⟩
]

/-- The floor of `m` at `n ≥ 21` on piece 2: `203/18`. -/
def mloR21S02 : Rat := R (203) 18

end Erdos993Lean.Analytic.MGF.Data
