import Erdos993Lean.Analytic.MGF.Pieces

/-!
# The MGF + two-sided atlas, rung 21, strip 42 (piece 42, activity `[29/20, 3/2]`, `m ∈ [35/6, 35/3]`)

Generated by `LEAN/lanes/A24/scratch/gen_mgf21.py` (lane A22's `gen_mgf.py` for rung 21) from lane M30's boxes `LEAN/atlas_mgf/rung_21/strip_42` (4 boxes, 1 slabs; SPEC v2 §4).
Boxes 0, 1, 2 are lane M30's boxes of the higher rung reused byte-identical (`rung_25/strip_42`, sha256 7eb831ef4bd8…, ac0fadca2a02…, d5c54255593b…); the other 1 boxes are new on `[35/6, 20/3]`.
The piece is `piece21 42` (`MGF/N21/Pieces.lean`: `θ = 7/10`, `D = 7/5`, rates `4481/10000, 521/1250, 3869/10000, 207/625, 701/2500`); the strip is
`[floor_21, floor_44] = [35/6, 35/3]`.  Each box carries its dual `(ν, c, α, β, γ, a, b, z)` centred at `m0` and its cutoff `N`.
The caps are lane M30's `rung_21/CAPS_N21.json` (sha256 `a11a7d149216850fff42b71aa1ab9feb82585274709a1f85f77956114212e47e`): `θ` and the tilts are Lean's N44 tables verbatim, `D` is
`D44` except lane O1R21's rows on pieces 24 (`21/20`) and 27 (`23/20`) (`MGF/N21/Pieces.lean`, `D21tab`); checked here per piece.
The box, COVER, SOURCE and VERIFIED files were checked against the rung-21 manifest
`LEAN/atlas_mgf/MANIFEST_RUNG_21.sha256` (sha256 of the manifest: `ef75ed56de6036b6fb10b9cbba0653325af517c1e099d5ab1554601e83e07b31`).
-/

namespace Erdos993Lean.Analytic.MGF.Data

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- strip_42/box_000000.json -/
def boxR21S42_000 : MBox :=
  ⟨R (29) 49, R (3) 5, R (115) 12, R (35) 3, R (85) 8,
   R (9902881893) 500000000000, R (-39066922127) 1000000000000,
   R (1063449571367534517260339168043065207767298437259) 10633823966279326983230456482242756608000000000000,
   R (6856762047) 1000000000000, R (293200239) 250000000000, R (120759545877) 1000000000000, R (1) 1,
   [R (839944361067) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 48⟩

/-- strip_42/box_000001.json -/
def boxR21S42_001 : MBox :=
  ⟨R (29) 49, R (3) 5, R (15) 2, R (115) 12, R (205) 24,
   R (10318114891) 250000000000, R (-18708637941) 250000000000,
   R (1558915725914080652124621336118719141265459529069) 10633823966279326983230456482242756608000000000000,
   R (944078611) 250000000000, R (460930047) 200000000000, R (0) 1, R (1) 1,
   [R (83617981103) 100000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 40⟩

/-- strip_42/box_000002.json -/
def boxR21S42_002 : MBox :=
  ⟨R (29) 49, R (3) 5, R (20) 3, R (15) 2, R (85) 12,
   R (12336242059) 250000000000, R (-2156604931) 25000000000,
   R (406561603777742871534311097279796412857817734071) 2658455991569831745807614120560689152000000000000,
   R (1090406799) 200000000000, R (586024979) 250000000000, R (0) 1, R (1) 1,
   [R (43366277277) 50000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 36⟩

/-- strip_42/box_000003.json -/
def boxR21S42_003 : MBox :=
  ⟨R (29) 49, R (3) 5, R (35) 6, R (20) 3, R (25) 4,
   R (32107497459) 500000000000, R (-20755770761) 200000000000,
   R (463343584951022648589476416473960207079378772301) 2658455991569831745807614120560689152000000000000,
   R (1758019433) 500000000000, R (2835201311) 1000000000000, R (0) 1, R (1) 1,
   [R (440201435517) 500000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 32⟩

/-- The boxes of the strip R21S42. -/
def boxesR21S42 : List MBox := [
  boxR21S42_000,
  boxR21S42_001,
  boxR21S42_002,
  boxR21S42_003
]

/-- The cover slabs of the strip R21S42. -/
def slabsR21S42 : List Atlas.Slab := [
  ⟨R (29) 49, R (3) 5, [3, 2, 1, 0]⟩
]

/-- The floor of `m` at `n ≥ 21` on piece 42: `35/6`. -/
def mloR21S42 : Rat := R (35) 6

end Erdos993Lean.Analytic.MGF.Data
