import Erdos993Lean.Analytic.MGF.Pieces

/-!
# The MGF + two-sided atlas, rung 21, strip 10 (piece 10, activity `[39/50, 4/5]`, `m ∈ [63/8, 27/2]`)

Generated by `LEAN/lanes/A24/scratch/gen_mgf21.py` (lane A22's `gen_mgf.py` for rung 21) from lane M30's boxes `LEAN/atlas_mgf/rung_21/strip_10` (3 boxes, 1 slabs; SPEC v2 §4).
Boxes 0, 1 are lane M30's boxes of the higher rung reused byte-identical (`rung_25/strip_10`, sha256 bef18eb1326a…, 783057b00f36…); the other 1 boxes are new on `[63/8, 9]`.
The piece is `piece21 10` (`MGF/N21/Pieces.lean`: `θ = 13/20`, `D = 7/5`, rates `817/2000, 3673/10000, 3437/10000, 187/625, 2559/10000`); the strip is
`[floor_21, floor_44] = [63/8, 27/2]`.  Each box carries its dual `(ν, c, α, β, γ, a, b, z)` centred at `m0` and its cutoff `N`.
The caps are lane M30's `rung_21/CAPS_N21.json` (sha256 `a11a7d149216850fff42b71aa1ab9feb82585274709a1f85f77956114212e47e`): `θ` and the tilts are Lean's N44 tables verbatim, `D` is
`D44` except lane O1R21's rows on pieces 24 (`21/20`) and 27 (`23/20`) (`MGF/N21/Pieces.lean`, `D21tab`); checked here per piece.
The box, COVER, SOURCE and VERIFIED files were checked against the rung-21 manifest
`LEAN/atlas_mgf/MANIFEST_RUNG_21.sha256` (sha256 of the manifest: `ef75ed56de6036b6fb10b9cbba0653325af517c1e099d5ab1554601e83e07b31`).
-/

namespace Erdos993Lean.Analytic.MGF.Data

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- strip_10/box_000000.json -/
def boxR21S10_000 : MBox :=
  ⟨R (39) 89, R (4) 9, R (45) 4, R (27) 2, R (99) 8,
   R (6811338453) 500000000000, R (25860270863) 1000000000000,
   R (1284362365896453691212168592952733951817944618617) 21267647932558653966460912964485513216000000000000,
   R (1287159009) 1000000000000, R (373202123) 1000000000000, R (1) 1, R (15857500417) 40000000000,
   [R (950106332817) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 112⟩

/-- strip_10/box_000001.json -/
def boxR21S10_001 : MBox :=
  ⟨R (39) 89, R (4) 9, R (9) 1, R (45) 4, R (81) 8,
   R (2047031177) 100000000000, R (30664143097) 1000000000000,
   R (15915418242071382602063696412926399703988359769) 212676479325586539664609129644855132160000000000,
   R (0) 1, R (186985849) 500000000000, R (1) 1, R (90052578951) 200000000000,
   [R (987773302413) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 96⟩

/-- strip_10/box_000002.json -/
def boxR21S10_002 : MBox :=
  ⟨R (39) 89, R (4) 9, R (63) 8, R (9) 1, R (135) 16,
   R (2068464051) 62500000000, R (67363036147) 1000000000000,
   R (548444472624573620719369121353984415549160282057) 5316911983139663491615228241121378304000000000000,
   R (-729929811) 200000000000, R (4841991) 10000000000, R (1) 1, R (76034970371) 1000000000000,
   [R (250588540301) 250000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 80⟩

/-- The boxes of the strip R21S10. -/
def boxesR21S10 : List MBox := [
  boxR21S10_000,
  boxR21S10_001,
  boxR21S10_002
]

/-- The cover slabs of the strip R21S10. -/
def slabsR21S10 : List Atlas.Slab := [
  ⟨R (39) 89, R (4) 9, [2, 1, 0]⟩
]

/-- The floor of `m` at `n ≥ 21` on piece 10: `63/8`. -/
def mloR21S10 : Rat := R (63) 8

end Erdos993Lean.Analytic.MGF.Data
