import Erdos993Lean.Analytic.MGF.Pieces

/-!
# The MGF + two-sided atlas, rung 21, strip 40 (piece 40, activity `[7/5, 57/40]`, `m ∈ [679/114, 679/57]`)

Generated by `LEAN/lanes/A24/scratch/gen_mgf21.py` (lane A22's `gen_mgf.py` for rung 21) from lane M30's boxes `LEAN/atlas_mgf/rung_21/strip_40` (4 boxes, 1 slabs; SPEC v2 §4).
Boxes 0, 1, 2 are lane M30's boxes of the higher rung reused byte-identical (`rung_25/strip_40`, sha256 73f4271c8785…, 3980dc123a1b…, 8a70da09af87…); the other 1 boxes are new on `[679/114, 388/57]`.
The piece is `piece21 40` (`MGF/N21/Pieces.lean`: `θ = 7/10`, `D = 7/5`, rates `4481/10000, 521/1250, 3869/10000, 207/625, 701/2500`); the strip is
`[floor_21, floor_44] = [679/114, 679/57]`.  Each box carries its dual `(ν, c, α, β, γ, a, b, z)` centred at `m0` and its cutoff `N`.
The caps are lane M30's `rung_21/CAPS_N21.json` (sha256 `a11a7d149216850fff42b71aa1ab9feb82585274709a1f85f77956114212e47e`): `θ` and the tilts are Lean's N44 tables verbatim, `D` is
`D44` except lane O1R21's rows on pieces 24 (`21/20`) and 27 (`23/20`) (`MGF/N21/Pieces.lean`, `D21tab`); checked here per piece.
The box, COVER, SOURCE and VERIFIED files were checked against the rung-21 manifest
`LEAN/atlas_mgf/MANIFEST_RUNG_21.sha256` (sha256 of the manifest: `ef75ed56de6036b6fb10b9cbba0653325af517c1e099d5ab1554601e83e07b31`).
-/

namespace Erdos993Lean.Analytic.MGF.Data

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- strip_40/box_000000.json -/
def boxR21S40_000 : MBox :=
  ⟨R (7) 12, R (57) 97, R (2231) 228, R (679) 57, R (1649) 152,
   R (3405081119) 200000000000, R (-1783929887) 50000000000,
   R (74114873985687574087551228595651539648206996803) 850705917302346158658436518579420528640000000000,
   R (6267490769) 1000000000000, R (1063036597) 1000000000000, R (32061932183) 250000000000, R (1) 1,
   [R (210865172447) 250000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 48⟩

/-- strip_40/box_000001.json -/
def boxR21S40_001 : MBox :=
  ⟨R (7) 12, R (57) 97, R (291) 38, R (2231) 228, R (3977) 456,
   R (18992676091) 500000000000, R (-9120509159) 125000000000,
   R (2806528660196573757210137247528987364460818641291) 21267647932558653966460912964485513216000000000000,
   R (1626017033) 500000000000, R (526348621) 250000000000, R (0) 1, R (1) 1,
   [R (52219168579) 62500000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 40⟩

/-- strip_40/box_000002.json -/
def boxR21S40_002 : MBox :=
  ⟨R (7) 12, R (57) 97, R (388) 57, R (291) 38, R (1649) 228,
   R (49746637849) 1000000000000, R (-90724046271) 1000000000000,
   R (3112593377428359490953558504134079053583566278071) 21267647932558653966460912964485513216000000000000,
   R (2357167711) 1000000000000, R (110239289) 50000000000, R (0) 1, R (1) 1,
   [R (876687088867) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 36⟩

/-- strip_40/box_000003.json -/
def boxR21S40_003 : MBox :=
  ⟨R (7) 12, R (57) 97, R (679) 114, R (388) 57, R (485) 76,
   R (15807725459) 250000000000, R (-104801388579) 1000000000000,
   R (3488508972683438098233862502267613928888887039091) 21267647932558653966460912964485513216000000000000,
   R (7843869) 20000000000, R (2400265351) 1000000000000, R (0) 1, R (1) 1,
   [R (899137417907) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 32⟩

/-- The boxes of the strip R21S40. -/
def boxesR21S40 : List MBox := [
  boxR21S40_000,
  boxR21S40_001,
  boxR21S40_002,
  boxR21S40_003
]

/-- The cover slabs of the strip R21S40. -/
def slabsR21S40 : List Atlas.Slab := [
  ⟨R (7) 12, R (57) 97, [3, 2, 1, 0]⟩
]

/-- The floor of `m` at `n ≥ 21` on piece 40: `679/114`. -/
def mloR21S40 : Rat := R (679) 114

end Erdos993Lean.Analytic.MGF.Data
