import Erdos993Lean.Analytic.MGF.Pieces

/-!
# The MGF + two-sided atlas, rung 21, strip 08 (piece 8, activity `[7/10, 3/4]`, `m ∈ [49/6, 14]`)

Generated by `LEAN/lanes/A24/scratch/gen_mgf21.py` (lane A22's `gen_mgf.py` for rung 21) from lane M30's boxes `LEAN/atlas_mgf/rung_21/strip_08` (3 boxes, 2 slabs; SPEC v2 §4).
Boxes 0, 1 are lane M30's boxes of the higher rung reused byte-identical (`rung_25/strip_08`, sha256 c6d3a59d07d2…, 03bca48b123d…); the other 1 boxes are new on `[49/6, 28/3]`.
The piece is `piece21 8` (`MGF/N21/Pieces.lean`: `θ = 7/10`, `D = 7/5`, rates `953/2500, 1787/5000, 669/2000, 182/625, 623/2500`); the strip is
`[floor_21, floor_44] = [49/6, 14]`.  Each box carries its dual `(ν, c, α, β, γ, a, b, z)` centred at `m0` and its cutoff `N`.
The caps are lane M30's `rung_21/CAPS_N21.json` (sha256 `a11a7d149216850fff42b71aa1ab9feb82585274709a1f85f77956114212e47e`): `θ` and the tilts are Lean's N44 tables verbatim, `D` is
`D44` except lane O1R21's rows on pieces 24 (`21/20`) and 27 (`23/20`) (`MGF/N21/Pieces.lean`, `D21tab`); checked here per piece.
The box, COVER, SOURCE and VERIFIED files were checked against the rung-21 manifest
`LEAN/atlas_mgf/MANIFEST_RUNG_21.sha256` (sha256 of the manifest: `ef75ed56de6036b6fb10b9cbba0653325af517c1e099d5ab1554601e83e07b31`).
-/

namespace Erdos993Lean.Analytic.MGF.Data

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- strip_08/box_000000.json -/
def boxR21S08_000 : MBox :=
  ⟨R (50) 119, R (3) 7, R (28) 3, R (14) 1, R (35) 3,
   R (2791092913) 125000000000, R (12769162997) 250000000000,
   R (501324772972073737957810953351094159501211132461) 5316911983139663491615228241121378304000000000000,
   R (0) 1, R (538481743) 1000000000000, R (1) 1, R (0) 1,
   [R (238077221569) 250000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 104⟩

/-- strip_08/box_000001.json -/
def boxR21S08_001 : MBox :=
  ⟨R (7) 17, R (50) 119, R (28) 3, R (14) 1, R (35) 3,
   R (22639887323) 1000000000000, R (24742931837) 500000000000,
   R (1111668001049681454080605955308944541767524676839) 10633823966279326983230456482242756608000000000000,
   R (177923963) 1000000000000, R (70324061) 125000000000, R (1) 1, R (0) 1,
   [R (95870252763) 100000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 104⟩

/-- strip_08/box_000002.json -/
def boxR21S08_002 : MBox :=
  ⟨R (7) 17, R (3) 7, R (49) 6, R (28) 3, R (35) 4,
   R (5638209633) 200000000000, R (30018373687) 500000000000,
   R (112826174579912080636812613245491306207989247433) 1063382396627932698323045648224275660800000000000,
   R (0) 1, R (498604217) 1000000000000, R (1) 1, R (0) 1,
   [R (989993763749) 1000000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 80⟩

/-- The boxes of the strip R21S08. -/
def boxesR21S08 : List MBox := [
  boxR21S08_000,
  boxR21S08_001,
  boxR21S08_002
]

/-- The cover slabs of the strip R21S08. -/
def slabsR21S08 : List Atlas.Slab := [
  ⟨R (7) 17, R (50) 119, [2, 1]⟩,
  ⟨R (50) 119, R (3) 7, [2, 0]⟩
]

/-- The floor of `m` at `n ≥ 21` on piece 8: `49/6`. -/
def mloR21S08 : Rat := R (49) 6

end Erdos993Lean.Analytic.MGF.Data
