import Erdos993Lean.Analytic.MGF.Pieces

/-!
# The MGF + two-sided atlas, rung 21, strip 09 (piece 9, activity `[3/4, 39/50]`, `m ∈ [623/78, 178/13]`)

Generated by `LEAN/lanes/A24/scratch/gen_mgf21.py` (lane A22's `gen_mgf.py` for rung 21) from lane M30's boxes `LEAN/atlas_mgf/rung_21/strip_09` (3 boxes, 1 slabs; SPEC v2 §4).
Boxes 0, 1 are lane M30's boxes of the higher rung reused byte-identical (`rung_25/strip_09`, sha256 237427faa6e7…, 9b42662f2161…); the other 1 boxes are new on `[623/78, 356/39]`.
The piece is `piece21 9` (`MGF/N21/Pieces.lean`: `θ = 7/10`, `D = 7/5`, rates `1959/5000, 3673/10000, 3437/10000, 187/625, 2559/10000`); the strip is
`[floor_21, floor_44] = [623/78, 178/13]`.  Each box carries its dual `(ν, c, α, β, γ, a, b, z)` centred at `m0` and its cutoff `N`.
The caps are lane M30's `rung_21/CAPS_N21.json` (sha256 `a11a7d149216850fff42b71aa1ab9feb82585274709a1f85f77956114212e47e`): `θ` and the tilts are Lean's N44 tables verbatim, `D` is
`D44` except lane O1R21's rows on pieces 24 (`21/20`) and 27 (`23/20`) (`MGF/N21/Pieces.lean`, `D21tab`); checked here per piece.
The box, COVER, SOURCE and VERIFIED files were checked against the rung-21 manifest
`LEAN/atlas_mgf/MANIFEST_RUNG_21.sha256` (sha256 of the manifest: `ef75ed56de6036b6fb10b9cbba0653325af517c1e099d5ab1554601e83e07b31`).
-/

namespace Erdos993Lean.Analytic.MGF.Data

@[noinline] private def R (n : Int) (d : Nat) : Rat := mkRat n d

/-- strip_09/box_000000.json -/
def boxR21S09_000 : MBox :=
  ⟨R (3) 7, R (39) 89, R (445) 39, R (178) 13, R (979) 78,
   R (2440348009) 200000000000, R (22423875457) 1000000000000,
   R (40243090781750521884394705526996355637815531771) 664613997892457936451903530140172288000000000000,
   R (281134829) 125000000000, R (398604049) 1000000000000, R (1) 1, R (403173149877) 1000000000000,
   [R (234577081119) 250000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 112⟩

/-- strip_09/box_000001.json -/
def boxR21S09_001 : MBox :=
  ⟨R (3) 7, R (39) 89, R (356) 39, R (445) 39, R (267) 26,
   R (12026048109) 500000000000, R (26167979459) 500000000000,
   R (187685112678945423656584190972800538845427380681) 2126764793255865396646091296448551321600000000000,
   R (0) 1, R (142899207) 250000000000, R (1) 1, R (85112185399) 1000000000000,
   [R (239201093897) 250000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 96⟩

/-- strip_09/box_000002.json -/
def boxR21S09_002 : MBox :=
  ⟨R (3) 7, R (39) 89, R (623) 78, R (356) 39, R (445) 52,
   R (14780479321) 500000000000, R (31720707401) 500000000000,
   R (16934230104422015911125993325667695017294100931) 166153499473114484112975882535043072000000000000,
   R (0) 1, R (140721589) 200000000000, R (1) 1, R (0) 1,
   [R (3852086881) 4000000000, R (0) 1, R (0) 1, R (0) 1, R (0) 1], 80⟩

/-- The boxes of the strip R21S09. -/
def boxesR21S09 : List MBox := [
  boxR21S09_000,
  boxR21S09_001,
  boxR21S09_002
]

/-- The cover slabs of the strip R21S09. -/
def slabsR21S09 : List Atlas.Slab := [
  ⟨R (3) 7, R (39) 89, [2, 1, 0]⟩
]

/-- The floor of `m` at `n ≥ 21` on piece 9: `623/78`. -/
def mloR21S09 : Rat := R (623) 78

end Erdos993Lean.Analytic.MGF.Data
